#!/bin/bash

# Move the sandbox.html file into place
mv /var/lib/drupal6/all/modules/sandbox/sandbox.html.hidden /var/lib/drupal6/all/modules/sandbox/sandbox.html

# Delete ALL the files from the sandbox dir
rm -rf /var/lib/drupal6/sandbox.scratchpads.eu/files/*

# Recreate the database.
echo "DROP DATABASE sandboxscratchpadseu; CREATE DATABASE sandboxscratchpadseu;" | mysql -uroot_with_drop -pOecey9cheehiphohngeiwi8lahH1ohNi

# Install via Firefox
Xvfb :3 -screen 0 800x600x16 -fbdir /tmp -nolisten inet6 2>/dev/null >/dev/null &
XVFB_PID=$!
DISPLAY=:3.0 firefox http://sandbox.scratchpads.eu/install.php?profile=sandbox_profile 2>/dev/null >/dev/null &
FIREFOX_PID=$!

# Check every 3 seconds to see if we have finished
#!/bin/bash
SANDBOX_INSTALLED=1
until [ $SANDBOX_INSTALLED -lt 1 ]
do
        sleep 3
        if [ -e /var/lib/drupal6/sandbox.scratchpads.eu/files/sandbox_installed ]
        then
                SANDBOX_INSTALLED=0
        fi
done
# Finally, really make sure we really have finished, by waiting a further 30
# seconds.
sleep 30
kill -9 $FIREFOX_PID $XVFB_PID 2>/dev/null >/dev/null

# Hide sandbox.html
mv /var/lib/drupal6/all/modules/sandbox/sandbox.html /var/lib/drupal6/all/modules/sandbox/sandbox.html.hidden