google.maps.__gjsload__('kml', function(_){var L6=function(a){this.data=a||[]},M6=function(a){this.data=a||[]},N6=function(a){this.data=a||[]},O6=function(a){this.data=a||[]},P6=function(a){this.data=a||[]},Q6=function(a){this.data=a||[]},R6=function(a){this.data=a||[]},S6=function(a){this.data=a||[]},T6=function(a){this.data=a||[]},U6=function(a){this.data=a||[]},V6=function(a){this.data=a||[]},W6=function(a){this.data=a||[]},X6=function(a){this.data=a||[]},Y6=_.oa("b"),Z6=function(a){this.f=0;this.b=[];this.j=a},$6=function(){_.Sf.call(this)},
a7=function(a){if(a.b){var b=a.b.getCenter();var c=a.get("projection"),d=a.get("bounds"),e=a.get("zoom");b=c&&d&&_.x(e)?_.Tk(c,d,e,_.$h,b):void 0;c=a.b;b=_.oc(Math.max(c.I,b.I),Math.max(c.J,b.J),Math.min(c.K,b.K),Math.min(c.L,b.L));b.W(a.f)||(a.set("croppedBounds",b),a.f=b)}},b7=function(a,b){return{b:function(b,d){if(d)return null;var c=null,f=b.latLng;a.forEach(function(a){if(!c){var b=a.get("bounds");b&&b.contains(f)&&0!=a.get("clickable")&&(c=a)}});return c},handleEvent:function(a,d,e){"mouseover"==
a?b.set("cursor","pointer"):"mouseout"==a&&b.set("cursor",null);_.G.trigger(e,a,new _.nk(d.latLng,d.va))},zIndex:10}},c7=function(a,b){_.Sf.call(this);this.f=a;this.b=b},d7=function(a){a.b.forEach(function(a){a.Ql=!0})},e7=function(a,b){var c=a.get("projection");a=a.get("zoom");return _.Mk(c,new _.z(0,b),a).lat()},f7=function(a,b,c){_.Sf.call(this);this.l=a;this.j=b;this.b=c;this.f=null;_.G.addListener(c,"insert",(0,_.t)(this.tk,this));_.G.addListener(c,"remove",(0,_.t)(this.Wh,this))},g7=function(a){a=
a.get("opacity");return _.Mb(a,1)},h7=function(a,b,c){this.b=_.Qj(_.Rm,a,c+"/maps/api/js/KmlOverlayService.GetFeature",b)},j7=function(a,b){return _.Fj(a,1)==i7.dg?_.N(a,0)*b:_.Fj(a,1)==i7.dj?b-_.N(a,0):_.N(a,0)},l7=function(a,b,c){return _.Fj(a,0)==k7.og?(a=_.Fj(new Q6(a.data[1]),1)==i7.dg?_.N(new Q6(a.data[1]),0)*b:_.N(new Q6(a.data[1]),0),a/c):1},m7=function(a,b,c,d){return _.Fj(a,0)==k7.Aj?b:_.Fj(a,0)==k7.og?j7(new Q6(a.data[1]),c):b*d},n7=function(a,b){this.f=b;this.b=this.j=null;_.G.bind(this.f,
"insert",this,this.pg);_.G.bind(this.f,"remove",this,this.qg)},o7=function(a,b){this.b=b;this.f=_.G.bind(a,"click",this,this.j)},r7=function(a){var b=a.get("map");0!=a.get("screenOverlays")?p7(a,b):q7(a,b)},s7=function(a){return a.get("url")?a.get("url"):a.get("driveFileId")?"docs://"+a.get("driveFileId"):null},v7=function(a,b,c){b.__gm.C||(b.__gm.C={},_.Fb({"false":_.tw,"true":_.Rw},function(a,c){b.__gm.C[a]=new Z6(new Y6(_.Qj(_.Rm,_.Ui,c+"/maps/api/js/KmlOverlayService.GetOverlays",_.yg)))}));if(a.C=
c){a.B=!0;var d=_.Qj(t7,_.Qj(u7,a,b,c));b.__gm.C[0==c.lastIndexOf("https://",0)].load(c,a.get("token")||null,d);_.pn(b,"Lk");_.rn("Lk","-p",a,!(!b||!b.Y));a.screenOverlays_changed=_.Qj(r7,a)}},u7=function(a,b,c,d,e,f,g,h,l,n){if(a.get("map")==b&&c==a.C&&a.B){a.B=!1;var q=s7(a);if(q&&q==c&&(a.set("status",g),g==_.ia)){a.b=h;a.f=l;e&&a.set("defaultViewport",e);a.set("metadata",f);a.F=n;c=0==c.lastIndexOf("https://",0);e=new h7(_.Ui,_.yg,c?_.Rw:_.tw);f=_.HB(e);g=new _.su;g.ma=d;g.Of=c;g.zIndex=a.get("zIndex")||
0;for(var r in n)g.parameters[r]=n[r];g.Te=(0,_.t)(f.load,f);g.eb=0!=a.get("clickable");a.l=g;_.rX.Ke(g,b);a.m||(a.m=_.G.addListener(g,"click",(0,_.t)(w7,a,a,b)));0!=a.get("screenOverlays")&&p7(a,b);for(d=0;d<a.f.length;++d)n=a.f[d],n.b.set("map",b),n.b.bindTo("clickable",a),x7(e,n,a,b);d=a.get("preserveViewport");e=a.get("defaultViewport");!d&&e&&b.fitBounds(e);b=new _.Pe;b=new o7(a,b);b.bindTo("map",a);b.bindTo("suppressInfoWindows",a);a.j=b;_.G.addListener(a,"clickable_changed",function(){a.l.eb=
0!=a.get("clickable")})}}},x7=function(a,b,c,d){var e=new _.cW(c.l.ma,b.ma);c=(0,_.t)(y7,c,c,d,b.b.get("bounds").getCenter(),null);a=(0,_.t)(a.load,a,e,c);b.listener=_.G.addListener(b.b,"click",a)},y7=function(a,b,c,d,e){var f={};f.latLng=c;f.pixelOffset=d;e.infoWindowHtml||(c=_.Y("div"),c.setAttribute("style","font-family: Roboto,Arial,sans-serif; font-size: small"),e.info_window_html?_.RA(c,e.info_window_html):e.name||e.description?(e.name&&(d=_.Y("div",c),d.setAttribute("style","font-weight: 500; font-size: medium; margin-bottom: 0em"),
_.nm(e.name,d)),e.description&&(d=_.Y("div",c),_.RA(d,e.description))):c=null,d="",c&&(d=window.document.createElement("div"),d.appendChild(c),d=d.innerHTML),e.infoWindowHtml=d);f.featureData=e;_.G.trigger(a,"click",f);_.rn("Lk","-i",e,!(!b||!b.Y))},w7=function(a,b,c,d,e,f){y7(a,b,d,e,f)},t7=function(a,b){if(b&&a&&0==b.getStatus()){for(var c=[],d=[],e={},f=0;f<_.Sd(b,5);++f){var g=new N6(_.Ij(b,5,f));if(_.Dj(g,5))d.push({b:new P6(g.data[5])});else if(_.Dj(g,4)){var h=z7(new _.yk((new O6(g.data[4])).data[1]));
h=new _.Xe((new M6((new O6(g.data[4])).data[0])).getUrl(),h);c.push({b:h,ma:g.getId()})}}g=_.O(b,1);h=z7(b.getDefaultViewport());f=new U6(b.data[3]);var l=new X6(f.data[3]),n={};n.name=_.O(l,0);n.email=_.O(l,2);n.uri=_.O(l,1);l={};l.name=_.O(f,0);l.description=_.O(f,1);l.snippet=_.O(f,2);l.author=n;l.hasScreenOverlays=!!d.length;a:{for(q in _.Vi)if(_.Fj(b,6)==A7[q]){var q=_.Vi[q];break a}q="UNKNOWN"}for(f=0;f<_.Sd(b,9);++f)n=new _.dW(_.Ij(b,9,f)),e[_.O(n,0)]=_.O(n,1);for(f=0;f<_.Sd(b,7);++f)n=new _.dW(_.Ij(b,
7,f)),e[_.O(n,0)]=_.O(n,1);a(g,h,l,q,d,c,e)}},B7=function(a){a.__gm.G||(a.__gm.G=new _.hd,(new n7(0,a.__gm.G)).bindTo("innerContainer",a.__gm));return a.__gm.G},q7=function(a,b){if(a.b){b=B7(b);for(var c=0;c<a.b.length;++c)b.remove(a.b[c])}},p7=function(a,b){if(a.b){b=B7(b);for(var c=a.b.length-1;0<=c;--c)_.id(b,a.b[c])}},z7=function(a){var b=new _.F(_.N(new _.vk(a.data[1]),0),_.N(new _.vk(a.data[1]),1));a=new _.F(_.N(new _.vk(a.data[0]),0),_.N(new _.vk(a.data[0]),1));return new _.Dc(a,b)},C7=_.k();var A7={UNKNOWN:0,OK:1,INVALID_REQUEST:2,DOCUMENT_NOT_FOUND:3,FETCH_ERROR:4,INVALID_DOCUMENT:5,DOCUMENT_TOO_LARGE:6,LIMITS_EXCEEDED:7,INTERNAL_ERROR:8,TIMED_OUT:9,Po:10};var D7;_.u(L6,_.M);_.u(M6,_.M);_.u(N6,_.M);_.u(O6,_.M);_.u(P6,_.M);_.u(Q6,_.M);_.u(R6,_.M);_.u(S6,_.M);_.u(T6,_.M);_.u(U6,_.M);_.u(V6,_.M);var E7;_.u(W6,_.M);_.u(X6,_.M);var i7={dg:0,To:1,dj:2},k7={Aj:0,So:1,og:2};L6.prototype.getUrl=function(){return _.O(this,0)};L6.prototype.setUrl=function(a){this.data[0]=a};M6.prototype.getUrl=function(){return _.O(this,0)};M6.prototype.setUrl=function(a){this.data[0]=a};N6.prototype.getId=function(){return _.O(this,0)};
V6.prototype.getStatus=function(){return _.Fj(this,0,-1)};V6.prototype.getDefaultViewport=function(){return new _.yk(this.data[4])};Y6.prototype.load=function(a,b,c){var d=new L6;d.setUrl(a);b&&(d.data[1]=b);D7||(D7={b:-1,A:[,_.V,_.V,_.S]});a=_.ui.b(d.data,D7);b=(0,_.t)(this.j,this,c);c=(0,_.t)(this.f,this,c);this.b(a,b,c)};Y6.prototype.f=function(a){a(null)};Y6.prototype.j=function(a,b){a(new V6(b))};Z6.prototype.load=function(a,b,c){this.f++;c=_.Sb((0,_.t)(this.l,this,c));this.j.load(a,b,c)};Z6.prototype.l=function(a,b){this.b.push((0,_.t)(a,null,b));this.f--;if(0==this.f){for(a=0;a<this.b.length;++a)this.b[a]();this.b=[]}};_.u($6,_.Sf);_.m=$6.prototype;_.m.projection_changed=function(){a7(this)};_.m.bounds_changed=function(){a7(this)};_.m.projectionBounds_changed=function(){this.O()};_.m.mapBounds_changed=function(){this.O()};
_.m.da=function(){var a=this.get("zoom"),b=this.get("projection");if(b&&_.x(a)){var c=this.get("projectionBounds");c&&(c=_.oc(c.I,c.J,c.K,c.L),a=_.Qk(b,a),b=(c.I+c.K)/2,a=b-_.Jb(b,0,Math.sqrt(a.x*a.x+a.y*a.y)),c.K-=a,c.I-=a,this.b&&_.tj(this.b,c)||(a=c.getCenter(),c=_.Lz(c),this.b=new _.nc([new _.z(a.x-c.width,a.y-c.height),new _.z(a.x+c.width,a.y+c.height)])),a7(this))}};_.u(c7,_.Sf);c7.prototype.changed=function(a){"bounds"!=a&&"zoom"!=a&&"projection"!=a||this.O()};
c7.prototype.da=function(){var a=this.get("projection"),b=this.get("bounds"),c=this.get("zoom");d7(this);if(a&&b&&_.x(c)&&!b.isEmpty()){var d=Math.round(b.J);b=Math.round(b.L);var e=this.get("projection"),f=this.get("zoom"),g=this.f;a=_.vj(g).lng();c=_.uj(g).lng();e=_.Ok(e,g,f);e=Math.round(_.Lz(e).width);g=g.getNorthEast().lat()-g.getSouthWest().lat();for(var h=e7(this,d),l=d;d<=b;++d){f=e7(this,d);var n=l,q=d,r=h,v=f,C=(r+v)/2,A=e7(this,(n+q)/2),y=Math.abs(d-l);if(1<=Math.abs((n-q)/(v-r)*(A-C))&&
10<y||d==b)h=new _.F(h,c),n=new _.F(f,a),l=new _.D(e,d-l),h=new _.Dc(n,h),n=g,q=_.vj(h).lat(),r=_.uj(h).lat(),r=l.height/(q-r),q=(_.vj(this.f).lat()-q)*r,n=Math.abs(n*r),q=new _.z(0,q),h=_.vj(h),_.id(this.b,{j:q,position:h,f:l,scaledSize:new _.D(l.width,n)}),l=d,h=f}}_.Sb((0,_.t)(this.j,this))()};c7.prototype.j=function(){this.b.forEach(function(a){a.Ql&&this.remove(a)})};_.u(f7,_.Sf);_.m=f7.prototype;_.m.changed=function(){this.O()};_.m.opacity_changed=function(){var a=g7(this);this.b.forEach(function(b){_.zm(b.node,a)})};_.m.da=function(){if(_.Pz(this.b)){var a=g7(this),b=this.get("projection"),c=this.get("zoom"),d=this.get("center"),e=this.get("offset"),f=this.get("latLngBounds");_.x(c)&&f&&b&&e&&d&&(f=_.Tk(b,f,c,e,d))&&!f.W(this.f)&&(this.f=f,this.b.forEach((0,_.t)(this.Wh,this)),this.b.forEach((0,_.t)(this.Vg,this,b,c,d,e,a)))}};
_.m.tk=function(a){var b=g7(this),c=this.get("projection"),d=this.get("zoom"),e=this.get("center"),f=this.get("offset");c&&_.x(d)&&f&&e&&this.Vg(c,d,e,f,b,a)};_.m.Vg=function(a,b,c,d,e,f){f.b=_.Sk(a,f.position,b,c,d.width,d.height,null);f.node=_.RB(this.l,this.j,f.j,f.f,f.b,f.scaledSize);_.um(f.node,10);_.zm(f.node,e)};_.m.Wh=function(a){a.node&&(_.kf(a.node),a.node=null)};h7.prototype.load=function(a,b){var c=new W6;c.data[0]=a.ma;c.data[1]=a.b+"";if(a.parameters)for(var d in a.parameters){var e=new _.dW(_.Rd(c,2));e.data[0]=d;e.data[1]=a.parameters[d]}E7||(E7={b:-1,A:[]},E7.A=[,_.V,_.V,_.Kd(_.hW())]);a=_.ui.b(c.data,E7);this.b(a,b,b);return a};h7.prototype.cancel=function(){throw Error("Not implemented");};_.u(n7,_.K);_.m=n7.prototype;_.m.innerContainer_changed=function(){var a=this.b;this.b=this.get("innerContainer");this.j&&(_.G.removeListener(this.j),delete this.j);a&&this.f.forEach((0,_.t)(this.qg,this));this.b&&(this.j=_.G.bind(this.b,"resize",this,this.An),this.f.forEach((0,_.t)(this.pg,this)))};_.m.An=function(){var a=this;_.Sb(function(){a.f.forEach((0,_.t)(a.zg,a))})()};
_.m.pg=function(a){if(this.b){var b=_.cg(this.b);b=_.Y("div",this.b,new _.z(b.width,b.height));_.qm(b);_.um(b,2);a.R=b;b=_.Y("div",a.R,new _.z(0,0),null,!0);_.qm(b);a.f=b;b={b:(0,_.t)(this.Oj,this,a)};a.ab=_.QB((new M6(a.b.data[0])).getUrl(),a.R,null,null,b)}};_.m.qg=function(a){a.R&&_.Wk(a.R);a.f&&_.Wk(a.f);a.ab&&_.Wk(a.ab);a.R=null;a.ab=null;a.f=null};_.m.Oj=function(a,b,c){a.R&&c&&(a.ab=c,_.qm(c),this.zg(a))};
_.m.zg=function(a){var b=_.cg(this.b);var c=_.cg(a.ab);c=new _.D(m7(new S6((new T6(a.b.data[3])).data[0]),c.width,b.width,l7(new S6((new T6(a.b.data[3])).data[1]),b.height,c.height)),m7(new S6((new T6(a.b.data[3])).data[1]),c.height,b.height,l7(new S6((new T6(a.b.data[3])).data[0]),b.width,c.width)));var d=j7(new Q6((new R6(a.b.data[2])).data[0]),b.width),e=j7(new Q6((new R6(a.b.data[2])).data[1]),b.height);e=b.height-e-c.height;_.mm(a.R,new _.z(d-j7(new Q6((new R6(a.b.data[1])).data[0]),c.width),
e+j7(new Q6((new R6(a.b.data[1])).data[1]),c.height)));_.Tf(a.R,c);_.Tf(a.ab,c);_.Tf(a.f,c)};_.u(o7,_.K);o7.prototype.remove=function(){this.b.close();_.G.removeListener(this.f);delete this.f};o7.prototype.changed=function(){this.b.close()};o7.prototype.suppressInfoWindows_changed=function(){this.get("suppressInfoWindows")&&this.b.close()};o7.prototype.j=function(a){if(a){var b=this.get("map");if(b&&!this.get("suppressInfoWindows")){var c=a.featureData;if(c=c&&c.infoWindowHtml||a.infoWindowHtml)this.b.setOptions({pixelOffset:a.pixelOffset,position:a.latLng,content:c}),this.b.open(b)}}};C7.prototype.f=function(a){var b=a.D,c=a.D=a.get("map"),d=s7(a);if(b){a.B=!1;a.l&&_.rX.Jf(a.l,b);a.m&&(_.G.removeListener(a.m),delete a.m);q7(a,b);delete a.screenOverlays_changed;if(a.f)for(b=0;b<a.f.length;++b){var e=a.f[b];e.b.set("map",null);_.G.removeListener(e.listener);delete e.listener}a.j&&(a.j.remove(),a.j.unbindAll(),delete a.j);_.sn("Lk","-p",a)}c&&v7(a,c,d)};
C7.prototype.b=function(a){var b=a.get("map"),c=b&&b.__gm;a.j&&a.j.B.remove(a);(a.j=c)&&_.id(c.B,a);if(c&&!c.S){var d=b7(c.B,c);c.S=d;_.Qz(c.f,d)}a.b&&(a.b.set("bounds",null),a.f.unbindAll(),a.b.unbindAll(),a.l.then(function(a){a.unbindAll()}),delete a.f,delete a.b,delete a.l,_.sn("Og","-p",a));if(b){var e=a.get("bounds"),f=a.get("url"),g=c.get("panes").overlayLayer,h=new _.hd;a.m=h;d=new $6;d.bindTo("projectionBounds",c);d.bindTo("projection",b);d.bindTo("zoom",b);d.set("bounds",e);a.f=d;var l=new c7(e,
h);l.bindTo("zoom",b);l.bindTo("projection",b);l.bindTo("bounds",d,"croppedBounds");a.b=l;a.l=window.Promise.resolve(function(){var d=new f7(f,g,h);d.bindTo("offset",c);d.bindTo("zoom",b);d.bindTo("center",c,"projectionCenterQ");d.bindTo("projection",b);d.bindTo("opacity",a);d.set("latLngBounds",e);return d}(null));_.pn(b,"Og");_.rn("Og","-p",a,!(!b||!b.Y));_.G.addListener(a,"click",function(){_.rn("Og","-i",a,!(!b||!b.Y))})}};_.je("kml",new C7);});

/*
     FILE ARCHIVED ON 21:55:23 Feb 07, 2018 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 08:46:00 Oct 02, 2018.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  LoadShardBlock: 26.965 (3)
  esindex: 0.006
  captures_list: 49.924
  CDXLines.iter: 14.489 (3)
  PetaboxLoader3.datanode: 307.368 (5)
  exclusion.robots: 0.286
  exclusion.robots.policy: 0.256
  RedisCDXSource: 1.796
  PetaboxLoader3.resolve: 46.653 (2)
  load_resource: 450.998
*/
