google.maps.__gjsload__('poly', function(_){var NX=function(a){for(a=a.toString(16);2>a.length;)a="0"+a;return a},OX=function(a){var b=a.length;!b||a[0]==a[b-2]&&a[1]==a[b-1]||(a.push(a[0]),a.push(a[1]))},PX=function(a,b){for(var c,d=0,e=a.length;d<e;d+=2)c=new _.F(a[d],a[d+1],!0),c=b.fromLatLngToPoint(c),a[d]=c.x,a[d+1]=c.y},QX=function(a,b,c){var d=a.path;a=a.b;for(var e=[],f=a?[]:null,g=d[0]==d[d.length-2]&&d[1]==d[d.length-1],h=0,l=d.length-2;h<l;h+=2){var n=d[h],q=d[h+1],r=d[h+2],v=d[h+3];if(a){var C=a[h/2];var A=a[h/2+1]}switch(b){case 0:var y=
  n>=c;var B=r>=c;break;case 1:y=n<=c;B=r<=c;break;case 2:y=q>=c;B=v>=c;break;case 3:y=q<=c,B=v<=c}!h&&y&&(e.push(n,q),a&&f.push(C));if(y!=B){switch(b){case 0:case 1:var E=(c-n)/(r-n);e.push(c,q+E*(v-q));break;case 2:case 3:E=(c-q)/(v-q),e.push(n+E*(r-n),c)}a&&f.push(C+E*(A-C))}B&&(e.push(r,v),a&&f.push(A))}g&&e.length&&(e[0]!=e[e.length-2]||e[1]!=e[e.length-1])&&(e.push(e[0],e[1]),a&&f.push(a[a.length-1]));return{path:e,b:f}},RX=function(a,b,c){for(var d=0,e=0,f=c.length;e<f;++e)d+=_.PH(a,b,c[e]);
  return!!(d&1)},SX=function(a,b,c,d){for(var e=null,f=c*c,g=0,h=d.length;g<h;++g){var l=a,n=b,q=c,r=d[g],v=r.length;if(!v||0>=q)var C=null;else{var A=0,y=q*q*1.01,B=[0,0];var E=r[A++]-l;var I=r[A++]-n;C=(E<-q?1:0)|(E>q?2:0)|(I<-q?4:0)|(I>q?8:0);var H=E*E+I*I;!C&&H<=y&&(y=H,B[0]=E,B[1]=I);for(;A<v;){var J=E;var ea=I;var ta=C;E=r[A++]-l;I=r[A++]-n;C=(E<-q?1:0)|(E>q?2:0)|(I<-q?4:0)|(I>q?8:0);if(!(ta&C)){H=E*E+I*I;!C&&H<=y&&(y=H,B[0]=E,B[1]=I);ta=E-J;var Ba=I-ea,za=ta*ta+Ba*Ba;if(!(1E-12>za)){var ab=E*
  ta+I*Ba;0>ab||ab>za||(H-=ab*ab/za,H<=y&&(y=H,za=1-ab/za,B[0]=J+ta*za,B[1]=ea+Ba*za))}}}B[0]+=l;B[1]+=n;B[2]=y;C=y<=q*q?B:null}C&&C[2]<=f&&(f=C[2],e=C)}return e},TX=function(a){var b=new _.dL(["mousemove","mouseup","mousewheel"]);_.pA(b,["offset","panes","projectionTopLeft","size"],a);return b},UX=function(a){var b=TX(a);_.G.addListener(b,"mousemove",_.Lc);_.G.addListener(b,"mouseup",_.Lc);_.G.addListener(b,"mousewheel",function(b){var c=a.get("mouseEventTarget");c&&_.G.trigger.apply(null,[c,"mousewheel"].concat(_.db(arguments,
  0)))});return b},VX=_.k(),XX=function(a){var b=["px","%"];if(!a||!_.Eb(b))return null;if("0"==a)return{value:0,b:b[0]};for(var c=0,d=b.length;c<d;++c){var e=b[c],f=(WX[e]=WX[e]||new RegExp("^(\\d+(?:\\.\\d+)?)"+e+"$")).exec(a);if(f)return{value:(0,window.parseFloat)(f[1]),b:e}}return null},YX=function(a,b,c){var d=a.fromPointToLatLng(c);a=a.fromPointToLatLng(new _.z(c.x+b,c.y+b));return Math.min(Math.abs(d.lat()-a.lat()),Math.abs(d.lng()-a.lng()))},ZX=function(a,b,c){this.x=a;this.y=b;this.z=c},aY=
  function(a){var b=Math.sqrt($X(a,a));1E-12>b||(a.x/=b,a.y/=b,a.z/=b)},$X=function(a,b){return a.x*b.x+a.y*b.y+a.z*b.z},bY=function(a,b,c){c.x=a.y*b.z-a.z*b.y;c.y=a.z*b.x-a.x*b.z;c.z=a.x*b.y-a.y*b.x},cY=function(a,b){var c=_.Cb(a[0]);a=_.Cb(a[1]);var d=Math.cos(c);b.x=Math.cos(a)*d;b.y=Math.sin(a)*d;b.z=Math.sin(c)},dY=function(a,b){var c=Math.atan2(a.y,a.x);b[0]=_.Db(Math.atan2(a.z,Math.sqrt(a.x*a.x+a.y*a.y)));b[1]=_.Db(c)},eY=function(a,b,c){c.x=a.x+b.x;c.y=a.y+b.y;c.z=a.z+b.z;aY(c)},gY=function(){var a=
  new _.Jg({clickable:!1,fillOpacity:0});a.bindTo("map",this);a.bindTo("strokeColor",this);a.bindTo("strokeOpacity",this);a.bindTo("strokeWeight",this);var b=["center","freeVertexPosition","freeVertexIsCenter"],c=new _.VB(b,"return",fY);_.pA(c,b,this);a.bindTo("center",c,"return");b=["center","radius","planetRadius","freeVertexPosition","freeVertexIsCenter"];c=new _.VB(b,"return",(0,_.t)(this.f,this));_.pA(c,b,this);a.bindTo("radius",c,"return");this.b=_.eL();this.b.bindTo("zIndex",this);a.bindTo("zIndex",
  this.b,"ghostZIndex")},fY=function(a,b,c){return c&&b||a},kY=function(a,b,c,d,e,f,g,h){var l=this,n=_.Y("div",a);n.style.display="none";a=9+2*(1+c);_.Tf(n,new _.D(a,a));g.construct(n,c,9,1,h?.5:1);var q=new _.WH(f);q.bindTo("position",l);f=new _.YG(n);f.bindTo("position",q,"rawPosition");f.bindTo("containerPixelBounds",l,"mapPixelBounds");f.bindTo("panningEnabled",l);f.set("draggableCursor",d);this.b=n;this.m=b;this.B=c;this.D=q;this.C=e;this.j=f;this.l=!1;this.f={};var r;this.P=[_.G.addListener(f,
  "dragstart",function(){q.set("referencePosition",l.get("position"));q.set("snappingCallback",l.C);l.f.mouseout=!0;l.f.mouseover=!0;r=[_.G.forward(b,"mousemove",n),_.G.forward(b,"mouseup",n)];b.set("draggableCursor",d);b.set("active",!0)}),_.G.addListener(f,"dragend",function(){q.set("referencePosition",null);q.set("snappingCallback",null);q.set("rawPosition",q.get("position"));b.set("active",!1);r&&(_.w(r,_.G.removeListener),r=null)}),_.G.forward(f,"panbynow",l),_.G.forward(f,"dragstart",l),_.G.forward(f,
  "dragend",l)];this.P.push(_.G.addListener(f,"mouseover",function(){l.l=!0;hY(l)}));this.P.push(_.G.addListener(f,"mouseout",function(){l.l=!1;hY(l)}));_.w(iY,function(a){l.P.push(jY(l,a))})},jY=function(a,b){function c(a){d.f[b]?d.f[b]=!1:(_.Nc(a),_.Oc(a),_.G.trigger(d,b,a))}var d=a;return"rightclick"==b?_.G.addDomListener(d.b,"contextmenu",c):_.G.addListener(d.j,b,c)},hY=function(a){if(a.l){var b=_.OL(a.get("color"));if(b){b.j=Math.floor((b.j+255)/2);b.f=Math.floor((b.f+255)/2);b.b=Math.floor((b.b+
  255)/2);var c=["#",NX(b.j),NX(b.f),NX(b.b)].join("")}}a.b.firstChild.style.backgroundColor=c||"white"},mY=function(a,b,c,d,e,f,g){function h(){l.l||_.G.trigger(l,"toolbar",{b:!1})}this.N=a;this.C=b;this.B=c;this.f=_.Y("div",e,_.Zh);this.l=d;this.G=f;this.H=g;this.b=[];a.forEach((0,_.t)(this.m,this));var l=this;this.D=[_.G.addListener(a,"insert_at",function(b){l.m(a.getAt(b),b);lY(l,b+1);h()}),_.G.addListener(a,"remove_at",function(a){var b=l.b[a];l.b.splice(a,1);l.F(b);lY(l,a);h()}),_.G.addListener(a,
  "set_at",function(b){l.b[b].f.set("latLngPosition",a.getAt(b));h()})]},lY=function(a,b){for(var c=a.b.length;b<c;++b)a.b[b].index=b},nY=function(a,b){this.m=a;this.B=b;this.l=null;this.f=!1;this.b=new _.gd;this.j=!1;_.G.bind(this.b,"set_at",this,this.Ao)},qY=function(a){var b=a.get("panes");if(!b)return null;b=new mY(a.b,oY,pY,!1,b.overlayMouseTarget,a.B,a.get("map"));b.bindTo("projection",a);b.bindTo("zoom",a);b.bindTo("projectionCenterQ",a);b.bindTo("panningEnabled",a);b.bindTo("mapPixelBounds",
  a);b.bindTo("color",a);b.bindTo("zIndex",a);b.bindTo("offset",a);var c=a.m;c.bindTo("freeVertexPosition",b);var d,e;_.G.addListener(b,"dragstart",function(b){d=a.get("center");e=a.get("radius");c.set("freeVertexIsCenter",0==b);c.set("map",a.get("map"))});_.G.addListener(b,"dragend",function(b,g){c.set("map",null);_.G.trigger(a,"toolbar",{b:!0,position:g,action:function(){a.set("center",d);a.set("radius",e)}})});_.G.forward(b,"dragstart",a);_.G.forward(b,"dragend",a);_.G.forward(b,"panbynow",a);return b},
  rY=function(a){var b=a.l;b&&(b.unbindAll(),b.release(),_.G.clearInstanceListeners(b),a.l=null)},sY=_.k(),vY=function(a,b,c){function d(){a.get("editable")?tY(a,b,c):(uY(a),_.G.trigger(a,"toolbar",{b:!1}))}a.editable_changed=function(){d()};d()},tY=function(a,b,c){if(!a.f){var d=new _.iL(a,!0);a.j=d;var e=new gY;e.bindTo("strokeColor",d);e.bindTo("strokeOpacity",d,"ghostStrokeOpacity");e.bindTo("strokeWeight",d);e.bindTo("center",a);e.bindTo("radius",a);e.bindTo("planetRadius",c);e.bindTo("zIndex",
  a);a.l=e;var f=b.__gm;a.Ra=UX(f);var g=_.KH(f,a),h=_.hm()?9:0,l=new sY;e=new nY(e,function(b,c,d,e){return new kY(b,a.Ra||null,h,c,g,d,l,e)});e.set("map",b);e.bindTo("center",a);e.bindTo("radius",a);e.bindTo("planetRadius",c);e.bindTo("panes",f);e.bindTo("projection",b);e.bindTo("zoom",f);e.bindTo("projectionCenterQ",f);e.bindTo("panningEnabled",b,"draggable");e.bindTo("mapPixelBounds",f,"pixelBounds");e.bindTo("offset",f);e.bindTo("color",d,"strokeColor");e.bindTo("zIndex",a);a.f=e;_.G.addListener(e,
  "dragstart",function(){a.set("capturing",!0)});_.G.addListener(e,"dragend",function(){a.set("capturing",!1)});_.G.forward(e,"panbynow",f);_.G.forward(e,"toolbar",a)}},uY=function(a){var b=a.f;b&&(b.unbindAll(),b.set("map",null),_.G.clearInstanceListeners(b),delete a.f,a.Ra.release(),delete a.Ra,a.set("capturing",!1),a.l.unbindAll(),delete a.l,a.j.release(),delete a.j)},wY=function(a,b,c,d,e,f){this.j=a;this.aa=c;a=a.get("center");b=c.fromDivPixelToLatLng(b);this.m=d(a,b);this.f=_.Oz(b,a);this.l=f},
  xY=function(){var a=this;_.Sf.call(a);var b=this.b=new _.Lg;b.f=!0;b.bindTo("capturing",a);b.bindTo("cursor",a);b.bindTo("map",a);b.bindTo("strokeColor",a);b.bindTo("strokeOpacity",a);b.bindTo("strokeWeight",a);b.bindTo("strokePosition",a);b.bindTo("fillColor",a);b.bindTo("fillOpacity",a);b.bindTo("clickable",a);b.bindTo("zIndex",a);b.bindTo("suppressUndo",a);var c=this.f=[];_.w(iY,function(d){c.push(_.G.forward(b,d,a))});c.push(_.G.forward(a,"toolbar",b))},yY=function(a,b){var c=Array(250),d=[c],
  e=_.Cb(a.lat()),f=_.Cb(a.lng()),g=Math.cos(b),h=Math.sin(b),l=Math.cos(e),n=Math.sin(e);if(1E-6<l)for(a=0;250>a;++a){var q=a/250*Math.PI*4;q+=Math.sin(q+Math.PI);var r=q/2,v=n*g+l*h*Math.cos(r);q=Math.asin(v);r=f+Math.atan2(Math.sin(r)*h*l,g-n*v);r=_.Jb(r,-Math.PI,Math.PI);c[a]=new _.F(_.Db(q),_.Db(r))}else for(f=_.Db(b),f=0<a.lat()?a.lat()-f:a.lat()+f,a=0;250>a;++a)c[a]=new _.F(f,360*a/250);e-b<-Math.PI/2&&(b=[new _.F(-90,-200,!0),new _.F(90,-200,!0),new _.F(90,-100,!0),new _.F(90,0,!0),new _.F(90,
  100,!0),new _.F(90,200,!0),new _.F(-90,200,!0),new _.F(-90,100,!0),new _.F(-90,0,!0),new _.F(-90,-100,!0),new _.F(-90,-200,!0)],d.push(b));return d},AY=function(a,b,c,d,e,f){this.f=a;this.aa=c;this.C=e;this.B=f;var g=zY(this);b=c.fromDivPixelToLatLng(b);this.D=_.Oz(g,b);this.F=d(g,b);var h=this.m=[];a.get("latLngs").forEach(function(a){var b=[];a.forEach(function(a){b.push({heading:d(g,a),ac:_.Oz(a,g)})});h.push(b)});this.j=g;this.l=b.lng()-g.lng()},zY=function(a){a=a.f.get("latLngs");var b=new ZX(0,
  0,0),c=new ZX(0,0,0);a.forEach(function(a){a.forEach(function(a){cY([a.lat(),a.lng()],c);b.x+=c.x;b.y+=c.y;b.z+=c.z})});aY(b);a=[0,0];dY(b,a);a[0]=_.Ib(a[0],-89,89);return new _.F(a[0],a[1])},BY=function(a,b,c,d,e){_.nk.call(this,a,b);_.p(c)&&(this.path=c);_.p(d)&&(this.vertex=d);_.p(e)&&(this.edge=e)},CY=function(a,b,c){this.j=a;this.aa=c;this.f=c.fromDivPixelToLatLng(b);var d=this.l=[];a.get("latLngs").forEach(function(a){d.push(_.db(a.getArray(),0))})},FY=function(a,b){this.C=a;this.f=_.Y("div",
  null,null,DY);this.f.style.backgroundColor="red";_.zm(this.f,.01);a=this.j=new _.YG(this.f);a.bindTo("position",this);a.bindTo("containerPixelBounds",this);a.bindTo("panningEnabled",this);a.set("draggableCursor","pointer");a.set("draggingCursor","pointer");a.set("size",DY);a.set("anchorPoint",EY);this.B=[_.G.bind(a,"dragstart",this,this.ng),_.G.bind(a,"dragend",this,this.De),_.G.bind(a,"click",this,this.Dj),_.G.bind(a,"mousedown",this,this.Hj),_.G.bind(a,"mousemove",this,this.Ij),_.G.bind(a,"mouseup",
  this,this.Jj),_.G.forward(a,"panbynow",this)];_.hm()&&(b=b.__gm,_.G.bind(b,"movestart",this,this.Fj),_.G.bind(b,"move",this,this.Gj),_.G.bind(b,"moveend",this,this.Ej));b=new _.VB(["mousedown","dragging"],"active",function(a,b){return a||b});b.bindTo("dragging",this,null,!0);b.bindTo("mousedown",this,null,!0);this.bindTo("active",b,null,!0)},GY=function(a,b){b=b?1E9:(a.b.get("zIndex")||0)-2;_.um(a.f,b)},HY=function(a,b,c){var d=a.get("position");d=a.aa.fromDivPixelToLatLng(d);_.G.trigger(a.b,b,new _.nk(d,
  c))},IY=function(a,b){function c(){var c=a.get("gestureHandling");null!=c?b.set("panningEnabled","none"!=c):b.set("panningEnabled",a.get("draggable"))}var d=a.__gm;_.G.addListener(a,"gesturehandling_changed",c);_.G.addListener(a,"draggable_changed",c);b.bindTo("panes",d);b.bindTo("projectionController",d);b.bindTo("containerPixelBounds",d,"pixelBounds");d.ja=_.G.forward(b,"panbynow",d)},JY=function(a,b){function c(){var b=a.getMap();a.getDraggable()&&(_.pn(b,"Od"),_.rn("Od","-p",a,!(!b||!b.Y)))}a.draggable_changed=
  c;c();a.D=[_.G.addListener(a,"mouseover",function(c){null==c.vertex&&null==c.edge&&b.set("poly",a)}),_.G.addListener(a,"click",function(b){null==b.vertex&&null==b.edge&&a.getDraggable()&&(b=a.getMap(),_.rn("Od","-i",a,!(!b||!b.Y)))}),_.G.addListener(a,"mouseout",function(a){null!=a.vertex||null!=a.edge||_.xj(a.va)||b.set("poly",null)})]},KY=function(a){var b=a.__gm.l;b.b||(_.Q("geometry",function(c){var d=new FY(function(a,b,d){return new wY(a,b,d,c.computeHeading,0,c.computeOffsetOrigin)},a);IY(a,
  d);b.b=function(b){JY(b,d);var c=b.pp=new _.VB(["baseMapType"],"planetRadius",_.Eg);c.bindTo("baseMapType",a.__gm);var e=b.Jg=new xY;e.set("map",a);e.bindTo("radius",b);e.bindTo("center",b);e.bindTo("capturing",b);e.bindTo("clickable",b);e.bindTo("cursor",b);e.bindTo("fillColor",b);e.bindTo("fillOpacity",b);e.bindTo("strokeColor",b);e.bindTo("strokeOpacity",b);e.bindTo("strokeWeight",b);e.bindTo("strokePosition",b);e.bindTo("zIndex",b);e.bindTo("suppressUndo",b);e.bindTo("planetRadius",c);b.ba=[];
  _.w(iY,function(a){b.ba.push(_.G.forward(e,a,b))});b.ba.push(_.G.forward(b,"toolbar",e));vY(b,a,c);_.pn(a,"Oc");_.rn("Oc","-p",b,!(!a||!a.Y));_.G.addListener(b,"click",function(){_.rn("Oc","-i",b,!(!a||!a.Y))})}}),b.onRemove=function(a){var b=a.Jg;b.unbindAll();b.set("map",null);b.release();delete a.Jg;_.w(a.ba,_.G.removeListener);delete a.ba;delete a.editable_changed;uY(a);_.sn("Oc","-p",a)})},LY=function(a,b,c,d){a.capturing_changed=function(){if(a.get("capturing"))if(0==a.get("clickable")){var e=
  a.b=new VX;e.bindTo("draggableCursor",a,"cursor");e.set("active",!0);b.bindTo("cursor",e);_.Qz(d,e)}else d.b=c,d.j=a;else a.b?(_.sj(d.l,a.b),a.b.unbindAll(),b.unbind("cursor"),b.set("cursor",""),delete a.b):d.b==c&&d.j==a&&(d.b=null,d.j=null)}},RY=function(a,b,c){var d=this;this.C=a;this.l=b;this.m=c;this.f={};this.b={};this.j=0;this.B=function(a){MY(d,this,a)};a.b=function(a){var b=d.get("projection");b=a.Zd={style:NY(d.m,a),dc:OY(a,b)};PY(d,a);a.changed=d.B;_.id(d.l,b)};a.onRemove=function(a){var b=
  a.Zd;delete a.Zd;d.l.remove(b);delete a.changed;QY(a);a=_.Xc(a);delete d.f[a];delete d.b[a]}},MY=function(a,b,c){var d=_.Xc(b);c in SY&&(a.b[d]=b,QY(b));c in TY&&(a.f[d]=b);UY(a)},UY=function(a){a.j||(a.j=_.Rb(function(){a.j=0;var b=a.f;a.f={};var c=a.b;a.b={};for(var d in b){var e=b[d],f=e.Zd;f.style=NY(a.m,e);f.Af&&!c[d]&&f.Af()}b=a.l;var g=a.get("projection");for(d in c)e=c[d],f=e.Zd,b.remove(f),f.dc=OY(e,g),_.id(b,f),PY(a,e)}))},PY=function(a,b){function c(){MY(e,b,"latLngs")}var d=b.get("latLngs");
  if(d){var e=a,f=_.Xc(b);a=d.getArray();for(var g=0,h=a.length;g<h;++g){var l=a[g];VY(l);l.f.Ma[f]=l.l.Ma[f]=l.j.Ma[f]=c}VY(d);d.l.Ma[f]=d.j.Ma[f]=function(a,b){WY(b,f);c()};d.f.Ma[f]=c}},QY=function(a){var b=a.get("latLngs");if(b){a=_.Xc(a);WY(b,a);b=b.getArray();for(var c=0,d=b.length;c<d;++c)WY(b[c],a)}},VY=function(a){a.f||(a.f=function(b){_.Fb(a.f.Ma,function(a,d){d(b)})},a.f.Ma={});a.l||(a.l=function(b,c){_.Fb(a.l.Ma,function(a,e){e(b,c)})},a.l.Ma={});a.j||(a.j=function(b,c){_.Fb(a.j.Ma,function(a,
  e){e(b,c)})},a.j.Ma={})},WY=function(a,b){a.f&&delete a.f.Ma[b];a.l&&delete a.l.Ma[b];a.j&&delete a.j.Ma[b]},bZ=function(){var a=this.f=_.Y("div");_.um(a,-202);_.tm(a,"pointer");_.ZA(a);this.b=_.RB(XY,a,YY,ZY);_.G.bind(this,"toolbar",this,this.Kj);_.G.X(a,"click",this,this.fn);_.G.addDomListener(a,"mouseover",(0,_.t)(this.ae,this,$Y));_.G.addDomListener(a,"mouseout",(0,_.t)(this.ae,this,YY));_.G.X(a,"mousedown",this,function(a){_.Oc(a);this.ae(aZ)});_.G.addDomListener(a,"mousemove",_.Oc);_.G.addDomListener(a,
  "mouseup",_.Oc)},cZ=function(a){a.j&&_.G.clearListeners(a.j,"suppressundo_changed")},IZ=function(a,b,c,d){a.ae(YY);_.mm(a.f,new _.z(b.x+dZ.x,b.y+dZ.y));a.l=c;cZ(a);a.j=d;_.rm(a.f);_.G.addListener(d,"suppressundo_changed",function(){d.get("suppressUndo")&&a.tc()})},JZ=function(a){var b=this;this.b=a;_.G.addListener(a,"set_at",function(c){_.G.trigger(b,"set_at",c);var d=a.getLength();0==c&&1<d&&_.G.trigger(b,"set_at",d)});_.G.addListener(a,"insert_at",function(c){_.G.trigger(b,"insert_at",c);var d=
  a.getLength();2==d?_.G.trigger(b,"insert_at",2):0==c&&1<d&&_.G.trigger(b,"set_at",d)});_.G.addListener(a,"remove_at",function(c){_.G.trigger(b,"remove_at",c);var d=a.getLength();1==d?_.G.trigger(b,"remove_at",1):0==c&&1<d&&_.G.trigger(b,"set_at",d)})},KZ=function(a,b,c){this.f=a;this.j=b;this.b=c;this.P=[_.G.bind(a,"set_at",this,this.bj),_.G.bind(a,"insert_at",this,this.eg),_.G.bind(a,"remove_at",this,this.aj)];b=0;for(a=a.getLength();b<a;++b)this.eg(b)},MZ=function(a,b,c){var d=a.get("projection");
  if(d){var e=a.f,f=e.getAt(c),g=a.j,h=a.get("geodesic");0<c&&g.setAt(c-1,LZ(e.getAt(c-1),f,h,d,a.b));c<e.getLength()-1&&(a=LZ(f,e.getAt(c+1),h,d,a.b),b?g.insertAt(c,a):g.setAt(c,a))}},LZ=function(a,b,c,d,e){c?d=e(a,b,.5):(180<Math.abs(a.lng()-b.lng())&&(a=new _.F(a.lat(),_.Jb(a.lng(),b.lng()-180,b.lng()+180),!0)),a=d.fromLatLngToPoint(a),b=d.fromLatLngToPoint(b),d=d.fromPointToLatLng(new _.z((a.x+b.x)/2,(a.y+b.y)/2)));return d},NZ=function(a,b,c,d){this.m=a;this.l=b;this.D=c;this.C=d;this.f=[];this.b=
  [];this.B=[]},PZ=function(a,b,c){var d=OZ(a,b,c,!1),e=a.m,f;_.G.addListener(d,"dragstart",function(c){f=b.getAt(c);var g=b.getArray(),l=a.l,n=g.length;if(2>n)e.set("anchors",[]);else{var q=g[l&&0==c?n-1:c-1];c=g[l&&c==n-1?0:c+1];g=[];q&&g.push(q);c&&g.push(c);e.set("anchors",g)}e.bindTo("freeVertexPosition",d);e.set("map",a.get("map"))});_.G.addListener(d,"dragend",function(c,d){e.set("map",null);_.G.trigger(a,"toolbar",{b:!0,position:d,action:function(){b.setAt(c,f)}})});return d},QZ=function(a,
  b,c){var d=new _.gd,e=a.l?new JZ(b):b,f=new KZ(e,d,a.C);f.bindTo("geodesic",a);f.bindTo("projection",a);var g=OZ(a,d,c,!0);g.j=f;var h=a.m;_.G.addListener(g,"dragstart",function(b){b=[e.getAt(b),e.getAt(b+1)];h.set("anchors",b);h.bindTo("freeVertexPosition",g);h.set("map",a.get("map"))});_.G.addListener(g,"dragend",function(c,e){b.insertAt(c+1,d.getAt(c));h.set("map",null);_.G.trigger(a,"toolbar",{b:!0,position:e,action:function(){b.removeAt(c+1)}})});return g},OZ=function(a,b,c,d){var e=new mY(b,
  ["pointer"],[0],d,c,a.D,a.get("map"));e.bindTo("projection",a);e.bindTo("zoom",a);e.bindTo("projectionCenterQ",a);e.bindTo("panningEnabled",a);e.bindTo("mapPixelBounds",a);e.bindTo("color",a);e.bindTo("zIndex",a);e.bindTo("offset",a);_.G.forward(e,"dragstart",a);_.G.forward(e,"dragend",a);_.G.forward(e,"panbynow",a);_.G.forward(e,"toolbar",a);_.w(iY,function(c){_.G.addListener(e,c,function(f){var g=b.getAt(f);if(a.l)for(var l=d?a.b:a.f,n=0;n<l.length;++n)if(l[n]==e){var q=n;break}_.G.trigger(a,c,
  new BY(g,void 0,q,d?void 0:f,d?f:void 0))})});return e},RZ=function(a){var b=(0,_.t)(a.j,a);_.w(a.f,b);_.w(a.b,b);a.f.length=0;a.b.length=0;_.w(a.B,_.G.removeListener);a.B.length=0},VZ=function(a,b,c){function d(){g[C++]=A.latLng[0];g[C++]=A.latLng[1];f&&(h[q++]=A.ac);l=A}var e=a.path,f=a.b;if(!e.length)return a;var g=Array(e.length),h=f?Array(f.length):null;a=[];var l=SZ();g[0]=l.latLng[0]=e[0];g[1]=l.latLng[1]=e[1];f&&(h[0]=l.ac=f[0]);l.depth=0;cY(l.latLng,l.Gc);for(var n=1,q=1,r=[],v=2,C=2;v<e.length||
  r.length;){if(r.length)var A=r.pop();else A=SZ(),A.depth=0,A.latLng[0]=e[v++],A.latLng[1]=e[v++],f&&(A.ac=f[n++]),cY(A.latLng,A.Gc);if(12<=Math.max(l.depth,A.depth))d();else{var y=new _.nc;y.I=Math.min(l.latLng[0],A.latLng[0]);y.K=Math.max(l.latLng[0],A.latLng[0]);y.J=Math.min(l.latLng[1],A.latLng[1]);y.L=Math.max(l.latLng[1],A.latLng[1]);if(_.lk(b,y)){var B=SZ();eY(l.Gc,A.Gc,B.Gc);dY(B.Gc,B.latLng);B.depth=Math.max(l.depth,A.depth)+1;f&&(B.ac=(l.ac+A.ac)/2);var E=y.J-1E-6,I=y.L+1E-6;y=B.latLng;y[1]=
  TZ(E,I,y[1]);UZ(l.latLng,A.latLng,a);Math.max(Math.abs(B.latLng[0]-a[0]),Math.abs(B.latLng[1]-a[1]))<=c?d():(r.push(A),r.push(B))}else d()}}return{path:g,b:h}},UZ=function(a,b,c){c[0]=(a[0]+b[0])/2;c[1]=(a[1]+b[1])/2},TZ=function(a,b,c){for(;c<a;)c+=360;for(;c>b;)c-=360;return c},SZ=function(){return{latLng:[0,0],Gc:new ZX(0,0,0)}},WZ=function(a){return function(b,c){if("px"==b.b)b=b.value/a;else{var d=_.Eb(c);b=d?b.value/100*c[d-1]:0}return b}},XZ=function(a,b,c,d){--b;if(!(0>b)){var e=a.length,
  f=0;for(d(0);f<b;){var g=1<<e,h=e?a[e-1][f/g]:0,l=f+g;l>=b&&(l=b);e&&c(f,l,h)?--e:(d(l),f=l,f&g||++e)}}},YZ=function(a,b){return function(c,d){if(0==c)return!0;c=a[c];d=a[d];for(var e=0,f;f=b[e];++e){var g=f.offset;if(f=f.repeat){if(Math.floor((c-g)/f)!=Math.floor((d-g)/f))return!0}else if(c<g&&g<=d)return!0}return!1}},ZZ=function(a,b,c,d){var e=a.I,f=a.J,g=a.K,h=a.L;return function(a,n,q){var l=d[2*a],v=d[2*a+1];a=d[2*n];n=d[2*n+1];var C=Math.min(v,n)-q,A=Math.max(l,a)+q,y=Math.max(v,n)+q;Math.min(l,
  a)-q<=g&&e<=A&&C<=h&&f<=y?q>b?q=!0:(C=c.fromLatLngToPoint(new _.F(l,v,!0)),A=c.fromLatLngToPoint(new _.F(a,n,!0)),C=c.fromPointToLatLng(new _.z((C.x+A.x)/2,(C.y+A.y)/2),!0),v=(v+n)/2,l=(l+a)/2-C.lat(),a=v-C.lng(),q=Math.sqrt(l*l+a*a)+q>b):q=!1;return q}},$Z=function(a,b,c){return function(d,e,f){var g=d.path,h=d.b,l=ZZ(a,b,c,g);d=l;if(h){var n=YZ(h,f);d=function(a,b,c){return l(a,b,c)||n(a,b)}}var q=[],r=h?[]:null;XZ(e,g.length/2,d,function(a){q.push(g[2*a],g[2*a+1]);h&&r.push(h[a])});return{path:q,
  b:r}}},a_=function(a,b){var c=0;_.Kb(a,-16,.001)&&(c|=1);_.Kb(a,272,.001)&&(c|=2);_.Kb(b,-16,.001)&&(c|=4);_.Kb(b,272,.001)&&(c|=8);return c},b_=function(a,b,c){b=this.l=1<<b;a=_.oc((256*a.x-16)/b,(256*a.y-16)/b,(256*(a.x+1)+16)/b,(256*(a.y+1)+16)/b);this.B=c;var d=new _.z(a.I,a.J);a=new _.z(a.K,a.L);d=c.fromPointToLatLng(d,!0);var e=c.fromPointToLatLng(a,!0);var f=Math.min(d.lat(),e.lat());a=Math.max(d.lat(),e.lat());var g=Math.min(d.lng(),e.lng());e=Math.max(d.lng(),e.lng());d=(g+e)/2;var h=_.Jb(d,
  -180,180);g+=h-d;e+=h-d;d=_.oc(f,g,a,e);f=new _.F(f,g,!0);g=new _.F(a,e,!0);a=c.fromLatLngToPoint(f);f=c.fromLatLngToPoint(g);a=new _.nc([a,f]);this.f=d;this.b=a;a=.5/b;d=this.b;this.m=Math.min(YX(c,a,new _.z(d.I,d.J)),YX(c,a,new _.z(d.K,d.L)));this.C=$Z(this.f,this.m,c);this.j=WZ(b)},c_=function(a,b,c,d){this.f=b;this.l=c;this.j=new _.HH(a.f,d)},d_=function(a){return _.Lb(a,function(a){return _.Lb(a,function(a){return Math.round(a)})})},g_=function(a,b,c,d){function e(){a.get("editable")?(e_(a,b,
  d),_.pn(b,"Oe"),_.rn("Oe","-p",a,!(!b||!b.Y))):(_.G.trigger(c,"toolbar",{b:!1,Bb:a}),f_(a))}a.editable_changed=function(){e()};e();a.m=_.G.addListener(a,"toolbar",function(b){b.Bb=a;_.G.trigger(c,"toolbar",b)})},e_=function(a,b,c){if(!a.l){var d=new _.iL(a,a.Ja);a.B=d;var e=new _.fL;e.bindTo("strokeColor",d);e.bindTo("strokeOpacity",d,"ghostStrokeOpacity");e.bindTo("strokeWeight",d);e.bindTo("geodesic",a);e.bindTo("zIndex",a);a.Ab=e;var f=b.__gm;a.Ra=UX(f);var g=_.KH(f,a),h=_.hm()?9:0,l=new sY,n=
  new NZ(e,a.Ja,function(b,c,d,e){return new kY(b,a.Ra||null,h,c,g,d,l,e)},c);n.set("map",b);n.bindTo("paths",a,"latLngs");n.bindTo("panes",f);n.bindTo("projection",b);n.bindTo("zoom",f);n.bindTo("projectionCenterQ",f);n.bindTo("panningEnabled",b,"draggable");n.bindTo("mapPixelBounds",f,"pixelBounds");n.bindTo("offset",f);n.bindTo("color",d,"strokeColor");n.bindTo("zIndex",a);n.bindTo("geodesic",a);n.bindTo("suppressGhostControlPoints",a);a.l=n;a.C=[_.G.addListener(a,"mousedown",function(){a.set("capturing",
  !0)}),_.G.addListener(a,"mouseup",function(){a.set("capturing",!1)})];_.G.addListener(a,"click",function(){a.get("editable")&&_.rn("Oe","-i",a,!(!b||!b.Y))});_.G.forward(n,"panbynow",f);_.G.forward(n,"toolbar",a);_.w(iY,function(b){_.G.forward(n,b,a)})}},f_=function(a){var b=a.l;b&&(b.unbindAll(),b.set("map",null),_.G.clearInstanceListeners(b),delete a.l,a.Ra.unbindAll(),a.Ra.release(),delete a.Ra,a.set("capturing",!1),_.w(a.C||[],_.G.removeListener),delete a.C,a.Ab.unbindAll(),delete a.Ab,a.B.release(),
  delete a.B)},h_=function(a,b,c){_.Sg.call(this);this.f=new _.D(256,256);this.l=Math.min(2,_.Vk());this.C=b;this.j=a;this.m=c||_.$i},k_=function(a,b,c,d){this.B=c;this.l=a;a=_.lm(a);this.b=i_(a,b,d);_.mm(this.b,_.Zh);this.m=j_(this.b,d);this.C=i_(a,b,d);this.D=j_(this.C,d);this.G=new _.$H(this.m);this.F=new _.$H(this.D);this.f={};this.j=0},i_=function(a,b,c){a=a.createElement("canvas");a.width=b.width*c;a.height=b.height*c;a.style.width=_.W(b.width);a.style.height=_.W(b.height);_.xm(a);return a},j_=
  function(a,b){a=a.context=a.getContext("2d");a.scale(b,b);a.lineCap=a.lineJoin="round";return a},n_=function(a){a.j||(a.j=_.Rb(function(){a.j=0;var b=l_(a);if(b.length){a.b.parentNode||a.l.appendChild(a.b);var c=a.m,d=a.D;c.clearRect(0,0,256,256);for(var e=null,f=0;f<b.length;++f){var g=b[f],h=g.f,l=h.B;_.Kb(1,l)?(a.B(c,g.b,h.m,h.f,h.b,h.j,h.C,h.D),m_(g.l,h.l,c,a.G,1)):(d.clearRect(0,0,256,256),a.B(d,g.b,h.m,h.f/l,h.b,h.j),m_(g.l,h.l,d,a.F,l),c.globalAlpha=l,c.drawImage(a.C,0,0,256,256));!e&&g.pa&&
  g.pa.na&&(e=g.pa.na)}e&&e()}else a.b.parentNode&&a.l.removeChild(a.b)}))},m_=function(a,b,c,d,e){for(var f=0,g=a.length;f<g;++f){var h=b[f],l=c,n=d,q=a[f],r=h.m,v=h.scale,C=h.f,A=h.D,y=h.C,B=h.j/e,E=h.l,I=h.B;h=h.b/e;l.beginPath();for(var H=0,J=q.length;H<J;H+=3)_.aI(n,r,q[H],q[H+1],C+(A?q[H+2]:0),v);h&&(l.fillStyle=I,l.globalAlpha=h,l.fill());E&&(l.lineWidth=E,l.strokeStyle=y,l.globalAlpha=B,l.stroke())}},l_=function(a){var b=[];a=a.f;for(var c in a)b.push(a[c]);b.sort(function(a,b){return a.zIndex-
  b.zIndex});return b},o_=function(a,b){function c(a,b){a.beginPath();for(var c=0,d;d=b[c];++c)if(d.length){a.moveTo(Math.round(d[0]),Math.round(d[1]));for(var e=2,f=d.length;e<f;)a.lineTo(Math.round(d[e++]),Math.round(d[e++]))}}var d=a.createElement("canvas");d.width=d.height=256*b;var e=d.getContext("2d");e.lineCap=e.lineJoin="round";e.scale(b,b);var f=[function(a,b,c,d,e){a.lineWidth=e;a.strokeStyle=c;a.globalAlpha=d;a.stroke()},function(a,b,c,d,e){a.lineWidth=2*e;a.strokeStyle=c;a.globalAlpha=d;
  a.save();a.clip();a.stroke();a.restore()},function(a,b,f,n,q){e.lineWidth=2*q;e.strokeStyle=f;e.globalCompositeOperation="source-over";e.clearRect(0,0,256,256);c(e,b);e.stroke();e.globalCompositeOperation="destination-out";e.fill();a.globalAlpha=n;a.drawImage(d,0,0,256,256)}];return function(a,b,d,e,q,r,v,C){c(a,b);C&&(a.fillStyle=v,a.globalAlpha=C,a.fill());if(q)f[r](a,b,d,e,q)}},p_=function(a,b){this.j=a;this.f=b;this.b=null},s_=function(a,b,c,d,e){var f=this;this.f=b;this.b=d;this.j=e;a.b=function(a){q_(f,
  a)};a.onRemove=function(a){delete a.Af;f.f.remove(a.Ea);a=a.dc;var b=a.ia;for(g in b){var c=b[g],d=c.pa,e=d.Ef;delete e.f[_.Xc(c)];n_(e);delete d.ia[_.Xc(c)]}a.ia={};var g=a.Kb;_.sn(g.Ja?"Op":"Ol","-v",g)};c.b=function(a){r_(f,a)};c.onRemove=function(a){f.b.remove(a.Ea);var b=a.ia,c;for(c in b){var d=b[c],e=d.j;delete e.ia[_.Xc(d)];d=e.Kb;_.sn(d.Ja?"Op":"Ol","-v",d)}a.ia={}};a=a.f;for(var g in a)q_(f,a[g]);c=c.f;for(g in c)r_(f,c[g])},q_=function(a,b){b.Af=function(){var a=b.dc.ia,c;for(c in a){var d=
  a[c];d.f=b.style;d.zIndex=b.style.zIndex;n_(d.pa.Ef)}};var c=b.dc,d=c.Ea;d.Bb=b;b.Ea=d;_.MH(a.f,d);d=a.b.search(d);for(var e=0,f=d.length;e<f;++e)t_(b,d[e].Sb||null);0<d.length&&(c=c.Kb,_.rn(c.Ja?"Op":"Ol","-v",c,a.j))},r_=function(a,b){var c=b.Ea;c.Sb=b;_.MH(a.b,c);c=a.f.search(b.Ea);if(0==c.length)b.na&&_.vb((0,_.t)(b.na,b));else for(var d=0,e=c.length;d<e;++d)t_(c[d].Bb||null,b),_.rn(c[d].Bb.dc.Kb.Ja?"Op":"Ol","-v",c[d].Bb.dc.Kb,a.j)},t_=function(a,b){for(var c=a.dc,d=b.bo,e=c.j,f=c.f,g=c.b,h,
  l=[],n=[],q=0,r=g.length;q<r;++q)n.push([]);q=0;for(r=e.length;q<r;++q){h=e[q];var v=h.f,C,A=d,y=g,B=v.b,E=[];if(B)for(var I=0;C=y[I];++I)E.push({offset:A.j(C.offset,B),repeat:A.j(C.repeat,B)});C=E;v=h.b?d.C(v,h.b,C):{path:_.db(v.path,0),b:v.b};if(v.path.length&&(f&&(v=VZ(v,d.f,d.m)),PX(v.path,d.B),h=d.b,v=QX(v,0,h.I),v=QX(v,1,h.K),v=QX(v,2,h.J),v=QX(v,3,h.L),A=v.path,A.length)){l.push(A);y=d.l;B=d.b.I;E=d.b.J;h=0;for(I=A.length;h<I;h+=2)A[h]=(A[h]-B)*y-16,A[h+1]=(A[h+1]-E)*y-16;for(h=0;y=C[h];++h){A=
  y.offset;y=y.repeat;if(B=v.b){E=v.path;I=[];for(var H=0,J=E.length-2;H<J;){var ea=E[H],ta=E[H+1],Ba=B[H/2],za=Ba-A;H+=2;var ab=E[H],pc=E[H+1];if(!(a_(ea,ta)&a_(ab,pc))){for(;_.Kb(ea,ab)&&_.Kb(ta,pc)&&H<J;)H+=2,ab=E[H],pc=E[H+1];var xc=B[H/2]-A,Uf=Math.atan2(ab-ea,ta-pc);0==Ba&&(za-=1E-9);if(y)for(Ba=Math.floor(xc/y)*y;Ba>za;){var Ae=(Ba-za)/(xc-za);I.push(ea+(ab-ea)*Ae,ta+(pc-ta)*Ae,Uf);Ba-=y}else 0>za&&0<=xc&&(za=(0-za)/(xc-za),I.push(ea+(ab-ea)*za,ta+(pc-ta)*za,Uf))}}A=I}else A=null;A&&(n[h]=n[h].concat(A))}}}l.length?
  (d={},d.b=l,d.l=n,d.f=a.style,d.zIndex=a.style.zIndex,d.pa=b,d.j=c,a=_.Xc(d),c.ia[a]=d,b.ia[a]=d,b=b.Ef,b.f[_.Xc(d)]=d,n_(b)):b.na&&_.vb((0,_.t)(b.na,b))},u_=function(a){return _.Lb(a,function(a){var b={},d=a.path;if(50<=d.length){for(var e=[],f=d.length-2,g,h=2;h<f;h<<=1){for(var l=d[0],n=d[1],q=Math.ceil(f/(2*h)),r=Array(q),v=0,C=0,A=d.length-1-h;v<A;){v+=h;var y=d[v],B=d[v+1];v+=h;v>d.length-2&&(v=d.length-2);var E=d[v],I=d[v+1],H=y-l,J=B-n;l=E-l;var ea=I-n,ta=H*l+J*ea;n=l*l+ea*ea;ta>=n?(y=E-y,
  B=I-B,B=y*y+B*B):0>=ta?B=H*H+J*J:(B=H*ea-J*l,B*=B,B/=n+1E-16);B=Math.sqrt(B);g&&(B+=Math.max(g[2*C],g[2*C+1]||0));r[C++]=B;l=E;n=I}C<q&&(r[C]=g?g[2*C]:0);g=r;e.push(r)}b.b=e}b.f=a;a=f=window.Infinity;e=g=-window.Infinity;h=0;for(q=d.length;h<q;)r=d[h++],a=Math.min(a,r),e=Math.max(e,r),r=d[h++],f=Math.min(f,r),g=Math.max(g,r);d=new _.nc;d.I=a;d.K=e;d.J=f;d.L=g;b.Ea=d;return b})},x_=function(a,b,c,d){return _.Lb(a,function(a){var e=a.path;a=a.b;var g=null;if(b){g=c?v_(e):w_(e,d);for(var h={0:0},l=0,
  n=[0],q=1,r=a.length;q<r;++q){var v=a[q];v in h?l=h[v]:(l+=g(q-1),h[v]=l);n.push(l)}g=n}return{path:e,b:g}})},w_=function(a,b){var c=_.db(a,0);PX(c,b);return function(a){a*=2;var b=c[a]-c[a+2];a=c[a+1]-c[a+3];return Math.sqrt(b*b+a*a)}},v_=function(a){return function(b){b*=2;var c=new _.F(a[b],a[b+1]);b=new _.F(a[b+2],a[b+3]);return _.Oz(c,b,1)}},B_=function(a){a.length&&(a=y_(a,z_),a=y_(a,A_));return a},y_=function(a,b){var c=[],d=new ZX(0,0,0),e=new ZX(0,0,0),f=new ZX(0,0,0),g=Array(a.length);g[0]=
  a[0];g[1]=a[1];cY(a,d);for(var h=2,l=2;h<a.length;){c[0]=a[h];c[1]=a[h+1];cY(c,f);b(d,f,e)&&(dY(e,c),g[l++]=c[0],g[l++]=c[1]);g[l++]=a[h++];g[l++]=a[h++];var n=d;d=f;f=n}return g},z_=function(a,b,c){if(0<a.z==0<b.z)return!1;bY(a,b,C_);bY(C_,D_,c);c.z=0;if(1E-12>$X(c,c))return!1;0>$X(c,a)+$X(c,b)&&(c.x=-c.x,c.y=-c.y);return!0},A_=function(a,b,c){bY(a,b,C_);bY(D_,C_,E_);bY(C_,E_,c);if(1E-12>$X(c,c)||0<$X(a,E_)==0<$X(b,E_))return!1;0>$X(c,a)+$X(c,b)&&(c.x=-c.x,c.y=-c.y,c.z=-c.z);return!0},G_=function(a,
  b,c){if(!b)return null;var d=[];b.forEach(function(a){d.push(F_(a))});a&&_.w(d,OX);if(c)for(a=0,b=d.length;a<b;++a)d[a]=B_(d[a]);return d},H_=function(a){return _.Lb(a,function(a){if(a.length){var b=a[1];for(var d=[0],e=1,f=1;e<a.length/2;++e,++f){var g=a[2*e+1];if(180<Math.abs(b-g)){var h=g<b?1:-1,l=a[2*e-2],n=a[2*e];a.splice(2*e,0,n,g+360*h,n,g+450*h,90,g+450*h,90,b-450*h,l,b-450*h,l,b-360*h);d.push(f,f,f,f,f,f-1);e+=6}d.push(f);b=g}b=d}else b=[];return{path:a,b:b}})},F_=function(a){a=a.b;for(var b=
  a.length,c=Array(2*b),d=0,e=0;d<b;++d){var f=a[d];c[e++]=f.lat();c[e++]=f.lng()}return c},OY=function(a,b){var c={},d=a.get("icons"),e=!a.Ja&&!!_.Eb(d),f=!0;c.b=[];e&&_.w(d,function(a){var b=XX(a.offset)||I_;a=XX(a.repeat)||J_;c.b.push({offset:b,repeat:a});f=f&&(0==b.value||"%"==b.b)&&(0==a.value||"%"==a.b)});d=c.f=a.get("geodesic");var g=G_(a.Ja,a.get("latLngs"),d);g=H_(g);var h=d&&f;d&&e&&!h&&(g=K_(g));g=x_(g,e,h,b);b=c.j=u_(g);if(1==b.length)e=b[0].Ea;else for(e=new _.nc,d=0,g=b.length;d<g;++d)_.Kz(e,
  b[d].Ea);c.Ea=e;c.Kb=a;c.ia={};return c},K_=function(a){return _.Lb(a,function(a){return VZ(a,_.ai,.1)})},L_=function(){var a=_.lI();this.j=_.hL;this.b=_.gL;this.f=a},NY=function(a,b){function c(a){return _.Mb(b.get(a),f[a])}var d={},e=d.Ja=b.Ja,f=e?a.b:a.j;d.m=c("strokeColor");d.f=c("strokeOpacity");d.b=c("strokeWeight");d.eb=c("clickable");e?(d.j=c("strokePosition"),d.C=c("fillColor"),d.D=c("fillOpacity")):d.j=a.b.strokePosition;var g=b.get("zIndex")||0;d.zIndex=1E3*g+_.Xc(b)%1E3;d.b=Math.min(d.b,
  0==d.j?32:16);d.F=b.get("hitStrokeWeight")||M_(d.b,d.j);d.l=[];d.B=1;if(!e){e=b.get("icons")||[];var h=a.f,l=0;_.w(e,function(a){var b=h(a.icon||{},d.m,d.f,d.b);b.D=!a.fixedRotation;d.l.push(b);l=Math.max(l,b.j);l=Math.max(l,b.b)});_.Kb(0,l)||(_.Kb(0,d.f)||_.Kb(0,d.b))&&1==d.l.length||(d.B=Math.max(l,d.f));_.Eb(e)&&(a=b.get("map"),_.pn(a,"Os"),_.rn("Os","-p",b,!(!a||!a.Y)))}return d},M_=function(a,b){switch(b){case 1:return 0;case 2:return 2*a;default:return a}},N_=function(a){var b=a.__gm.D;if(!b.b){var c=
  a.__gm,d=new _.hd;(new RY(b,d,new L_)).bindTo("projection",a);var e=_.oc(-100,-200,100,200),f=new _.hd;new s_(d,new _.LH(e),f,new _.LH(e),!(!a||!a.Y));d=_.lm(a.getDiv());d=new p_(new _.D(256,256),d);e=(0,_.t)(d.l,d);d=a.__gm;e=new h_(f,e,void 0);e.bindTo("projection",a);e=e.b();e=_.vd(e);var g=new c_(f,c,function(b){return a.getProjection().fromPointToLatLng(b)},e);_.Qz(d.f,g);_.JH(a,e,"overlayLayer",30);var h=new bZ;h.bindTo("panes",c);h.bindTo("projection",a);h.bindTo("zoom",c);h.bindTo("projectionCenterQ",
  c);h.bindTo("offset",c);_.G.bind(a,"click",h,h.tc);_.Q("geometry",function(d){var e=new FY(function(a,b,c){return a.get("geodesic")?new AY(a,b,c,d.computeHeading,d.computeOffset,d.computeOffsetOrigin):new CY(a,b,c)},a);IY(a,e);_.G.addListener(b,"insert",function(b){JY(b,e);g_(b,a,h,d.interpolate);LY(b,c,g,a.__gm.f);if(!b.f){var f=b.Ja?"Op":"Ol";_.pn(a,f);_.rn(f,"-p",b,!(!a||!a.Y))}_.G.addListener(b,"click",function(){b.Ja?b.f||_.rn("Op","-i",b,!(!a||!a.Y)):_.rn("Ol","-i",b,!(!a||!a.Y))})})});_.G.addListener(b,
  "remove",function(a){_.w(a.D||[],_.G.removeListener);delete a.draggable_changed;delete a.D;_.sn("Od","-p",a);delete a.editable_changed;f_(a);_.G.trigger(h,"toolbar",{b:!1,Bb:a});a.m&&(_.G.removeListener(a.m),delete a.m);_.sn("Oe","-p",a);a.set("capturing",!1);delete a.capturing_changed;if(!a.f)if(a.Ja)_.sn("Op","-p",a);else{_.sn("Ol","-p",a);var b=a.get("icons");_.Eb(b)&&_.sn("Os","-p",a)}})}},O_=function(a,b,c){if(!a||!b||!c)return null;var d=c.lat(),e=c.lng();c=b&1?d:a.f.b;var f=b&2?e:a.b.b;d=b&
  4?d:a.f.f;var g=b&8?e:a.b.f;if(c>d){var h=c;c=d;d=h}b&10&&!a.b.contains(e)&&(h=_.uc(e,a.b.b),a=_.uc(a.b.f,e),b&2?h>a:a>h)&&(h=f,f=g,g=h);return _.Ec(c,f,d,g)},P_=function(){var a=new _.Ng({clickable:!1,fillOpacity:0});a.bindTo("map",this);a.bindTo("strokeColor",this);a.bindTo("strokeOpacity",this);a.bindTo("strokeWeight",this);var b=new _.VB(["bounds","freeControlPoint","freeVertexPosition"],"return",O_);b.bindTo("bounds",this);b.bindTo("freeControlPoint",this);b.bindTo("freeVertexPosition",this);
  a.bindTo("bounds",b,"return");this.b=_.eL();this.b.bindTo("zIndex",this);a.bindTo("zIndex",this.b,"ghostZIndex")},Q_=function(a,b){this.C=a;this.B=b;this.j=this.m=null;this.f=new _.gd;_.G.bind(this.f,"set_at",this,this.yo);this.l=new _.gd;_.G.bind(this.l,"set_at",this,this.zo);this.b=!1},X_=function(a,b,c){var d=c?new mY(a.f,R_,S_,!1,b.overlayMouseTarget,a.B,a.get("map")):new mY(a.l,T_,U_,!0,b.overlayMouseTarget,a.B,a.get("map"));d.bindTo("projection",a);d.bindTo("zoom",a);d.bindTo("projectionCenterQ",
  a);d.bindTo("panningEnabled",a);d.bindTo("mapPixelBounds",a);d.bindTo("color",a);d.bindTo("zIndex",a);d.bindTo("offset",a);var e=a.C,f=c?V_:W_,g;_.G.addListener(d,"dragstart",function(b){g=a.get("bounds");e.bindTo("freeVertexPosition",d);e.set("freeControlPoint",f[b]);e.set("map",a.get("map"))});_.G.addListener(d,"dragend",function(b,c){e.set("map",null);_.G.trigger(a,"toolbar",{b:!0,position:c,action:function(){a.set("bounds",g)}})});_.G.forward(d,"dragstart",a);_.G.forward(d,"dragend",a);_.G.forward(d,
  "panbynow",a);return d},Y_=function(a){a&&(a.unbindAll(),a.release(),_.G.clearInstanceListeners(a))},Z_=function(a,b,c){a.b||(a.b=!0,b=O_(a.get("bounds"),b,c),a.set("bounds",b),a.b=!1)},b0=function(a,b){function c(){a.get("editable")?$_(a,b):(a0(a),_.G.trigger(a,"toolbar",{b:!1}))}a.editable_changed=function(){c()};c()},$_=function(a,b){if(!a.f){var c=new _.iL(a,!0);a.j=c;var d=new P_;d.bindTo("strokeColor",c);d.bindTo("strokeOpacity",c,"ghostStrokeOpacity");d.bindTo("strokeWeight",c);d.bindTo("bounds",
  a);d.bindTo("zIndex",a);a.l=d;var e=b.__gm;a.Ra=UX(e);var f=_.KH(e,a),g=_.hm()?9:0,h=new sY;d=new Q_(d,function(b,c,d,e){return new kY(b,a.Ra||null,g,c,f,d,h,e)});d.set("map",b);d.bindTo("bounds",a);d.bindTo("panes",e);d.bindTo("projection",b);d.bindTo("zoom",e);d.bindTo("projectionCenterQ",e);d.bindTo("panningEnabled",b,"draggable");d.bindTo("mapPixelBounds",e,"pixelBounds");d.bindTo("offset",e);d.bindTo("color",c,"strokeColor");d.bindTo("zIndex",a);d.bindTo("suppressGhostControlPoints",a);a.f=d;
  _.G.addListener(d,"dragstart",function(){a.set("capturing",!0)});_.G.addListener(d,"dragend",function(){a.set("capturing",!1)});_.G.forward(d,"panbynow",e);_.G.forward(d,"toolbar",a)}},a0=function(a){var b=a.f;b&&(b.unbindAll(),b.set("map",null),_.G.clearInstanceListeners(b),delete a.f,a.Ra.release(),delete a.Ra,a.set("capturing",!1),a.l.unbindAll(),delete a.l,a.j.release(),delete a.j)},c0=function(a,b,c){this.j=a;this.aa=c;a=a.get("bounds");this.m=a.getSouthWest();this.l=a.getNorthEast();this.f=
  c.fromDivPixelToLatLng(b)},d0=function(){var a=this,b=this.b=new _.Lg;b.f=!0;b.bindTo("capturing",a);b.bindTo("cursor",a);b.bindTo("map",a);b.bindTo("strokeColor",a);b.bindTo("strokeOpacity",a);b.bindTo("strokeWeight",a);b.bindTo("strokePosition",a);b.bindTo("fillColor",a);b.bindTo("fillOpacity",a);b.bindTo("clickable",a);b.bindTo("zIndex",a);b.bindTo("suppressUndo",a);var c=this.f=[];_.w(iY,function(d){c.push(_.G.forward(b,d,a))});c.push(_.G.forward(a,"toolbar",b))},e0=function(a){var b=a.__gm.F;
  if(!b.b){var c=new FY(function(a,b,c){return new c0(a,b,c)},a);IY(a,c);b.b=function(b){JY(b,c);var d=b.Uh=new d0;d.set("map",a);d.bindTo("bounds",b);d.bindTo("capturing",b);d.bindTo("cursor",b);d.bindTo("clickable",b);d.bindTo("fillColor",b);d.bindTo("fillOpacity",b);d.bindTo("strokeColor",b);d.bindTo("strokeOpacity",b);d.bindTo("strokeWeight",b);d.bindTo("strokePosition",b);d.bindTo("suppressUndo",b);d.bindTo("zIndex",b);var f=b.ba=[];_.w(iY,function(a){f.push(_.G.forward(d,a,b))});f.push(_.G.forward(b,
  "toolbar",d));b0(b,a);_.pn(a,"Or");_.rn("Or","-p",b,!(!a||!a.Y));_.G.addListener(b,"click",function(){_.rn("Or","-i",b,!(!a||!a.Y))})};b.onRemove=function(a){var b=a.Uh;b.unbindAll();b.set("map",null);b.release();delete a.Uh;_.w(a.ba,_.G.removeListener);delete a.ba;delete a.editable_changed;a0(a);_.sn("Or","-p",a)}}},f0=_.k(),iY="click dblclick mousedown mousemove mouseout mouseover mouseup rightclick".split(" ");_.u(VX,_.K);VX.prototype.b=function(){return this.get("active")?this:null};
  VX.prototype.handleEvent=function(a,b,c){if("mouseout"==a)this.set("cursor","");else if("mouseover"==a){var d=this.get("draggableCursor");d&&this.set("cursor",d)}_.G.trigger(c,a,new _.nk(b.latLng,b.va))};VX.prototype.zIndex=window.Infinity;var WX={};ZX.prototype.W=function(a){return this.x==a.x&&this.y==a.y&&this.z==a.z};_.u(gY,_.K);gY.prototype.f=function(a,b,c,d,e){return!e&&d&&a?_.Oz(d,a,c):b};_.u(kY,_.K);kY.prototype.release=function(){_.kf(this.b);_.w(this.P,_.G.removeListener);this.P.length=0;this.j.unbindAll();this.j.release();this.D.unbindAll();this.m.set("active",!1)};kY.prototype.position_changed=function(){var a=this.get("position");if(a){this.b.style.display="block";var b=5+this.B;_.mm(this.b,new _.z(a.x-b,a.y-b))}else this.b.style.display="none"};kY.prototype.color_changed=function(){var a=this.get("color");this.b.firstChild.style.borderColor=a;hY(this)};_.u(mY,_.K);mY.prototype.release=function(){_.w(this.D,_.G.removeListener);this.D.length=0;_.w(this.b,(0,_.t)(this.F,this));this.b.length=0;_.G.clearInstanceListeners(this.f);_.kf(this.f)};mY.prototype.zIndex_changed=function(){var a=this.get("zIndex")||0;this.l&&--a;_.um(this.f,a)};
  mY.prototype.m=function(a,b){function c(a){var b=e.index,c=f.get("pixelPosition");_.G.trigger(d,a,b,c)}var d=this,e={};e.index=b;d.b.splice(b,0,e);var f=new _.JG;f.bindTo("projection",d);f.bindTo("zoom",d);f.bindTo("center",d,"projectionCenterQ");f.bindTo("offset",d);f.set("latLngPosition",a);e.f=f;var g=this.G(d.f,d.C[b%d.C.length],d.B[b%d.B.length],d.l);g.bindTo("position",f,"pixelPosition");g.bindTo("color",d);g.bindTo("panningEnabled",d);g.bindTo("mapPixelBounds",d);e.b=g;var h=[_.G.addListener(g,
  "dragstart",function(){d.bindTo("freeVertexPosition",f,"latLngPosition");c("dragstart")}),_.G.addListener(g,"dragend",function(){d.N.setAt(e.index,f.get("latLngPosition"));c("dragend")}),_.G.forward(g,"panbynow",d)];_.w(iY,function(a){h.push(_.G.addListener(g,a,function(){c(a)}))});e.ba=h};mY.prototype.F=function(a){a.b.unbindAll();a.b.release();a.f.unbindAll();_.w(a.ba,_.G.removeListener);a.ba.length=0};_.u(nY,_.K);var oY=["pointer","row-resize","row-resize","col-resize","col-resize"],pY=[0,2,2,1,1];_.m=nY.prototype;_.m.map_changed=function(){this.get("map")||(this.m.set("map",null),rY(this),_.G.clearInstanceListeners(this.b))};_.m.panes_changed=function(){rY(this);this.l=qY(this)};
  _.m.If=function(){var a=this.b,b=this.get("center"),c=this.get("radius");if(b&&_.x(c)){this.j=!0;var d=this.get("planetRadius"),e=_.Db(c/d);var f=_.Cb(b.lat());if(d=c/d){c=Math.cos(d);d=Math.sin(d);var g=Math.sin(f);f=Math.atan2(Math.sin(Math.acos((1-c)/d*Math.tan(f)))*d*Math.cos(f),c-g*g)}else f=0;f=_.Db(f);a.setAt(0,b);c=b.lat()+e;90>c?a.setAt(1,new _.F(c,b.lng())):a.setAt(1,null);e=b.lat()-e;-90<e?a.setAt(2,new _.F(e,b.lng())):a.setAt(2,null);180>=f?(e=b.lng()+f,f=b.lng()-f,a.setAt(3,new _.F(b.lat(),
  e)),a.setAt(4,new _.F(b.lat(),f))):(a.setAt(3,null),a.setAt(4,null));this.j=!1;this.f||_.G.trigger(this,"toolbar",{b:!1})}else a.clear()};_.m.center_changed=nY.prototype.If;_.m.radius_changed=nY.prototype.If;_.m.planetRadius_changed=nY.prototype.If;
  _.m.Ao=function(a){if(!this.j){var b=this.b.getAt(a);if(0==a)_.oA(this,function(){this.f=!0;this.set("center",b);this.f=!1},0);else{var c=_.Oz(this.get("center"),b,this.get("planetRadius"));_.oA(this,function(){this.f=!0;this.set("radius",c);this.f=!1},0)}}};sY.prototype.construct=function(a,b,c,d,e){a=_.Y("div",a,new _.z(b,b),new _.D(c,c));a.style.borderWidth=_.W(d);a.style.borderStyle="solid";a.style.borderRadius=_.W(Math.ceil(c/2+d));_.zm(a,e)};var g0=new _.F(90,0),h0=new _.F(-90,0);wY.prototype.b=function(a){a=this.aa.fromDivPixelToLatLng(a);var b=this.l(a,this.f,this.m);b||(b=Math.abs(_.Oz(a,g0)-this.f)<Math.abs(_.Oz(a,h0)-this.f)?g0:h0);this.j.set("center",b)};_.u(xY,_.Sf);_.m=xY.prototype;_.m.center_changed=xY.prototype.O;_.m.radius_changed=xY.prototype.O;_.m.planetRadius_changed=xY.prototype.O;_.m.da=function(){var a=this.b;if(a){var b=this.get("radius"),c=this.get("center");_.x(b)&&c?(b/=this.get("planetRadius"),a.setPaths(yY(c,b))):a.setPaths([])}};_.m.release=function(){for(var a=this.f,b=0,c=a.length;b<c;++b)_.G.removeListener(a[b]);this.f=null;this.b.unbindAll();this.b=null};AY.prototype.b=function(a){var b=this;a=b.aa.fromDivPixelToLatLng(a);var c=this.B(a,this.D,this.F);c?89<Math.abs(c.lat())&&(c=new _.F(_.Ib(c.lat(),-89,89),c.lng())):c=new _.F(this.j.lat(),a.lng()-this.l);b.f.get("latLngs").forEach(function(a,e){for(var d=0,g=a.getLength();d<g;++d){var h=b.C(c,b.m[e][d].ac,b.m[e][d].heading);a.setAt(d,h)}});this.j=c;this.l=a.lng()-c.lng()};_.u(BY,_.nk);CY.prototype.b=function(a){var b=this.j.get("latLngs"),c=this.aa,d=c.fromLatLngToDivPixel(this.f),e=new _.z(d.x-a.x,d.y-a.y);_.w(this.l,function(a,d){var f=b.getAt(d);_.w(a,function(a,b){a=c.fromLatLngToDivPixel(a);a.x-=e.x;a.y-=e.y;f.setAt(b,c.fromDivPixelToLatLng(a))})})};_.u(FY,_.K);FY.prototype.release=function(){this.j.unbindAll();this.j.release();this.B&&_.w(this.B,_.G.removeListener);this.B=null;this.P&&_.w(this.P,_.G.removeListener);this.P=null;this.f&&_.Wk(this.f);this.f=null};var DY=new _.D(30,30),EY=new _.z(DY.width/2,DY.height/2);_.m=FY.prototype;
  _.m.be=function(){if(!this.get("active")&&!this.m){var a=this.get("panes"),b=this.get("projectionController"),c=this.get("poly");if(a!=this.l||b!=this.aa||c!=this.b)this.l=a,this.aa=b,this.b=c,this.P&&_.w(this.P,_.G.removeListener),this.P=null,this.l&&this.aa&&this.b?(this.P=_.hm()?[_.G.bind(this.b,"mousedown",this,this.Qm),_.G.bind(this.b,"mouseup",this,this.Sm)]:[_.G.bind(this.b,"mousemove",this,this.Rm)],this.bindTo("draggable",this.b)):(this.unbind("draggable"),this.set("draggable",!1))}};
  _.m.active_changed=FY.prototype.be;_.m.panes_changed=FY.prototype.be;_.m.poly_changed=FY.prototype.be;_.m.projectionController_changed=FY.prototype.be;_.m.draggable_changed=function(){this.get("draggable")&&!_.hm()?(this.l.overlayMouseTarget.appendChild(this.f),GY(this,!!this.get("active"))):this.f&&this.f.parentNode&&this.f.parentNode.removeChild(this.f)};_.m.Dj=function(a){_.Oc(a);HY(this,"click",a)};_.m.Hj=function(a){this.set("mousedown",!0);GY(this,!0);HY(this,"mousedown",a)};
  _.m.Jj=function(a){GY(this,!1);this.set("mousedown",!1);HY(this,"mouseup",a)};_.m.Ij=function(a){this.get("active")?_.Oc(a):HY(this,"mousemove",a)};_.m.Rm=function(a){if(a=a.va)a=_.on(a,this.l.overlayMouseTarget),this.set("position",a)};_.m.ng=function(){var a=this.get("position");this.set("dragging",!0);this.F=this.C(this.b,a,this.aa);this.b.set("capturing",!0);HY(this,"dragstart");this.D=this.b.get("editable");this.b.set("editable",!1)};
  _.m.De=function(){this.b.set("editable",this.D);HY(this,"dragend");this.b.set("capturing",!1);this.set("dragging",!1)};_.m.position_changed=function(){var a=this.get("position");_.hm()||_.mm(this.f,new _.z(a.x-EY.x,a.y-EY.y));this.get("dragging")&&(this.F.b(a),HY(this,"drag"))};_.m.Fj=function(a){!this.m||!this.b||a instanceof _.fq&&_.jq(a)||this.get("dragging")||(a=this.aa.fromLatLngToDivPixel(a.latLng),this.set("position",a),this.ng(),this.j.set("dragging",!0))};
  _.m.Gj=function(a){if(this.get("dragging")){if(a instanceof _.fq&&1!=a.scale)this.De();else if(this.m){var b=this.aa.fromLatLngToDivPixel(a.latLng);this.set("position",b)}a instanceof _.fq&&_.UB(a)}};_.m.Ej=function(a){this.get("dragging")&&(this.De(),this.j.set("dragging",!1),a instanceof _.fq&&_.UB(a))};_.m.Qm=function(){this.m=!!this.get("draggable")};_.m.Sm=function(){this.m=!1};_.u(RY,_.K);RY.prototype.projection_changed=function(){var a=this;a.C.forEach(function(b){if(b.get("icons")){var c=_.Xc(b);a.b[c]=b;QY(b)}});UY(a)};var SY={latLngs:1,geodesic:1,icons:1},TY={strokeColor:1,strokeOpacity:1,strokePosition:1,strokeWeight:1,fillColor:1,fillOpacity:1,hitStrokeWeight:1,zIndex:1,clickable:1,icons:1};_.u(bZ,_.K);_.m=bZ.prototype;_.m.panes_changed=function(){var a=this.f,b=this.get("panes");b?b.floatPane.appendChild(a):a.parentNode&&_.kf(a)};_.m.tc=function(){_.ZA(this.f);this.l=null;cZ(this);this.j=null};_.m.changed=bZ.prototype.tc;_.m.Kj=function(a){a.b?a.Bb.get("suppressUndo")?this.tc():IZ(this,a.position,a.action,a.Bb):a.Bb==this.j&&this.tc()};_.m.fn=function(a){_.Nc(a);_.Oc(a);this.l();this.tc()};_.m.ae=function(a){_.SB(this.b,ZY,a)};
  var XY=_.Jm("undo_poly"),ZY=new _.D(30,27),YY=_.Zh,$Y=new _.z(30,0),aZ=new _.z(60,0),dZ=new _.z(10,-11);JZ.prototype.getLength=function(){var a=this.b.getLength();1<a&&++a;return a};JZ.prototype.getAt=function(a){this.b.getLength()==a&&1<a&&(a=0);return this.b.getAt(a)};_.u(KZ,_.K);_.m=KZ.prototype;_.m.release=function(){_.w(this.P,_.G.removeListener)};_.m.rn=function(){var a=this.get("projection"),b=this.j;if(a)for(var c=this.f,d=c.getLength(),e=this.get("geodesic"),f=0;f<d-1;++f)b.setAt(f,LZ(c.getAt(f),c.getAt(f+1),e,a,this.b));else b.clear()};_.m.geodesic_changed=KZ.prototype.projection_changed=KZ.prototype.rn;_.m.bj=function(a){MZ(this,!1,a)};_.m.eg=function(a){MZ(this,!0,a)};
  _.m.aj=function(a){var b=this.get("projection");if(b){var c=this.f,d=this.j,e=this.get("geodesic");a<c.getLength()?(0<a&&d.setAt(a-1,LZ(c.getAt(a-1),c.getAt(a),e,b,this.b)),d.removeAt(a)):0<a&&d.removeAt(a-1)}};_.u(NZ,_.K);NZ.prototype.map_changed=function(){this.get("map")||(this.m.set("map",null),RZ(this))};
  NZ.prototype.panes_changed=NZ.prototype.paths_changed=NZ.prototype.suppressGhostControlPoints_changed=function(){var a=this;RZ(a);var b=a.get("paths"),c=a.get("panes");if(b&&c){var d=c.overlayMouseTarget;b.forEach(function(b){a.f.push(PZ(a,b,d));a.get("suppressGhostControlPoints")||a.b.push(QZ(a,b,d))});var e=function(){_.G.trigger(a,"toolbar",{b:!1})};e();c=a.B;c.push(_.G.addListener(b,"insert_at",function(c){var f=a.get("suppressGhostControlPoints"),h=b.getAt(c);a.f.splice(c,0,PZ(a,h,d));f||a.b.splice(c,
  0,QZ(a,h,d));e()}));c.push(_.G.addListener(b,"remove_at",function(b){var c=a.get("suppressGhostControlPoints");a.j(a.f[b]);a.f.splice(b,1);c||(a.j(a.b[b]),a.b.splice(b,1));e()}));c.push(_.G.addListener(b,"set_at",function(c){var f=a.get("suppressGhostControlPoints");a.j(a.f[c]);var h=b.getAt(c);a.f[c]=PZ(a,h,d);f||(a.j(a.b[c]),a.b[c]=QZ(a,h,d));e()}))}};NZ.prototype.j=function(a){a.unbindAll();a.release();_.G.clearInstanceListeners(a);a.j&&(a.j.release(),a.j.unbindAll())};b_.prototype.getBounds=_.pa("f");var i0=new _.z(.5,.5);
  c_.prototype.b=function(a,b){var c=_.IH(this.j,a.fa,i0,!1);if(!c)return null;var d=new _.z(256*c.Cc.T,256*c.Cc.U),e=new _.z(256*c.Nc.T,256*c.Nc.U),f=1<<c.Nc.$,g=[];c=c.pa.ia;for(var h in c)g.push(c[h]);g.reverse();g.sort(function(a,b){return b.zIndex-a.zIndex||0});h=null;c=b?15:0;for(var l=0,n=g.length;l<n;++l){var q=g[l],r=q.f;if(r.eb){var v=q.j.Kb,C=r.F/2+c;q=d_(q.b);if(C=SX(d.x,d.y,C,q)){h=v;b=a.fa=new _.z((C[0]+e.x)/f,(C[1]+e.y)/f);a.latLng=this.l(b);break}if(r.Ja&&!b&&RX(d.x,d.y,q)){h=v;break}}}return h};
  c_.prototype.handleEvent=function(a,b,c){if("mouseout"==a)this.f.set("cursor","");else if("mousemove"==a){var d=c.get&&c.get("cursor");_.p(d)||(d="pointer");this.f.set("cursor",d)}_.G.trigger(c,a,new BY(b.latLng,b.va))};c_.prototype.zIndex=30;_.Oj(h_,_.Sg);h_.prototype.b=function(){return{tileSize:{Na:this.f.width,Oa:this.f.height},Ua:this.m,Ca:!0,rb:2,xa:this.B.bind(this)}};
  h_.prototype.B=function(a,b){var c=this;b=void 0===b?{}:b;var d=!1,e=window.document.createElement("div");_.Tf(e,this.f);var f=new _.z(a.T,a.U),g=this.get("projection");g=new b_(f,a.$,g);var h=g.getBounds(),l=this.C(this.l,e),n={Ea:h,Z:f,R:e,Ef:l,ia:{},na:function(){d=!0;b.na&&b.na()},bo:g,zoom:a.$};_.id(this.j,n);return{Z:a,ga:function(){return e},lb:function(){return d},release:function(){_.om(e,"");c.j.remove(n);b.za&&b.za()},freeze:_.k()}};p_.prototype.l=function(a,b){this.b=this.b||o_(this.f,a);return new k_(b,this.j,this.b,a)};var D_=new ZX(0,0,1),C_=new ZX(0,0,0),E_=new ZX(0,0,0);var I_={value:100,b:"%"},J_={value:0,b:"px"};_.u(P_,_.K);_.u(Q_,_.K);var V_=[12,6,9,3],W_=[1,2,4,8],R_=["ne-resize","nw-resize","se-resize","sw-resize"],T_=["row-resize","col-resize"],S_=[0],U_=[2,1];_.m=Q_.prototype;_.m.map_changed=function(){this.get("map")||(this.C.set("map",null),Y_(this.m),this.get("suppressGhostControlPoints")||Y_(this.j),_.G.clearInstanceListeners(this.f))};
  _.m.panes_changed=Q_.prototype.suppressGhostControlPoints_changed=function(){Y_(this.m);Y_(this.j);this.j=null;var a=this.get("panes");a&&(this.m=X_(this,a,!0),this.get("suppressGhostControlPoints")||(this.j=X_(this,a,!1)))};
  _.m.bounds_changed=function(){var a=this.f,b=this.l,c=this.get("bounds");if(c){this.b=!0;a.setAt(0,c.getNorthEast());a.setAt(1,_.vj(c));a.setAt(2,_.uj(c));a.setAt(3,c.getSouthWest());a=c.f.Jb();var d=c.b.Jb();b.setAt(0,new _.F(c.f.b,d));b.setAt(1,new _.F(a,c.b.b));b.setAt(2,new _.F(c.f.f,d));b.setAt(3,new _.F(a,c.b.f));this.b=!1;_.G.trigger(this,"toolbar",{b:!1})}else a.clear(),b.clear()};_.m.yo=function(a){Z_(this,V_[a],this.f.getAt(a))};_.m.zo=function(a){Z_(this,W_[a],this.l.getAt(a))};c0.prototype.b=function(a){var b=this.aa,c=b.fromLatLngToDivPixel(this.f),d=b.fromLatLngToDivPixel(this.m);b=b.fromLatLngToDivPixel(this.l);b=new _.z(b.x-c.x+a.x,b.y-c.y+a.y);a=new _.Dc(this.aa.fromDivPixelToLatLng(new _.z(d.x-c.x+a.x,d.y-c.y+a.y)),this.aa.fromDivPixelToLatLng(b));this.j.set("bounds",a)};_.u(d0,_.K);d0.prototype.bounds_changed=function(){var a=this.b;if(a){var b=this.get("bounds");if(b){var c=b.getSouthWest(),d=b.getNorthEast();b=b.getCenter();a.setPaths([new _.F(d.lat(),d.lng()),new _.F(d.lat(),b.lng()),new _.F(d.lat(),c.lng()),new _.F(c.lat(),c.lng()),new _.F(c.lat(),b.lng()),new _.F(c.lat(),d.lng())])}else a.setPaths([])}};d0.prototype.release=function(){for(var a=this.f,b=0,c=a.length;b<c;++b)_.G.removeListener(a[b]);delete this.f;this.b.unbindAll();delete this.b};f0.prototype.b=function(a){var b=0!=a.getVisible()?a.getMap():null;a.b!=b&&(a.b&&a.b.__gm.l.remove(a),b&&(KY(b),_.id(b.__gm.l,a)),a.b=b)};f0.prototype.f=function(a){var b=0!=a.getVisible()?a.getMap():null;a.j!=b&&(a.j&&a.j.__gm.D.remove(a),b&&(N_(b),_.id(b.__gm.D,a)),a.j=b)};f0.prototype.j=function(a){var b=0!=a.getVisible()?a.getMap():null;a.b!=b&&(a.b&&a.b.__gm.F.remove(a),b&&(e0(b),_.id(b.__gm.F,a)),a.b=b)};_.je("poly",new f0);});

  /*
       FILE ARCHIVED ON 18:01:29 Feb 11, 2018 AND RETRIEVED FROM THE
       INTERNET ARCHIVE ON 08:48:25 Oct 02, 2018.
       JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

       ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
       SECTION 108(a)(3)).
  */
  /*
  playback timings (ms):
    LoadShardBlock: 41.892 (3)
    esindex: 0.006
    captures_list: 57.563
    CDXLines.iter: 8.492 (3)
    PetaboxLoader3.datanode: 97.422 (5)
    exclusion.robots: 0.147
    exclusion.robots.policy: 0.138
    RedisCDXSource: 0.422
    PetaboxLoader3.resolve: 240.676
    load_resource: 299.71
  */
