<?php

/**
 * Implements hook_help().
 */
function scratchpad_relationt_help($path, $arg){
  if($path == 'admin/help#scratchpad_relation'){return t('Set ecological relationships.');}
}

/**
 * Implements hook_menu().
 */
function scratchpad_relations_menu(){
  $items = array();
  $items['admin/content/scratchpad_relations/%'] = array(
    'title' => 'Scratchpad relations',
    'description' => 'View, edit and delete any of the available relations on your site.',
    'page callback' => 'scratchpad_relations_admin_content',
    'page arguments' => array(
      3
    ),
    'access arguments' => array(
      'administer Scratchpad relations'
    ),
    'file' => 'scratchpad_relations.admin.inc',
    'type' => MENU_LOCAL_TASK
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function scratchpad_relations_theme($existing, $type, $theme, $path){
  $theme = array(
    'scratchpad_relations_admin_content' => array(
      'variables' => array(
        'relations' => NULL
      ),
      'file' => 'scratchpad_relations.admin.inc'
    ),
    'relation_select_field' => array(
      'variables' => array(
        'entity' => NULL,
        'relation' => NULL,
        'entity_type' => NULL,
        'items' => NULL,
        'related_entities' => NULL,
        'bundle' => NULL,
        'field_name' => NULL,
        'list_type' => NULL
      ),
      'template' => 'relation-select-field',
      'path' => $path . '/theme'
    )
  );
  return $theme;
}

function scratchpad_relations_preprocess_relation_select_field(&$variables, $hook){
  $id = $variables['entity']->tid;
  $relation = $variables['relation'];
  $relation_type = relation_type_load($relation->relation_type);
  $label = $relation_type->directional ? $relation_type->reverse_label : $relation_type->label;
  foreach($relation->endpoints[LANGUAGE_NONE] as $endpoint){
    if($endpoint['entity_type'] == $variables['entity_type'] && $endpoint['entity_id'] == $id){
      if($endpoint['r_index'] == 0){
        $label = $relation_type->label;
      }
    }
  }
  $variables['items'] = array();
  foreach($variables['related_entities'] as $related_entity){
    $link = entity_uri($related_entity->entity_type, $related_entity);
    $variables['items'][] = $label . ' ' . l(entity_label($related_entity->entity_type, $related_entity), $link['path']);
  }
  $variables['theme_hook_suggestions'][] = 'relation_select_field__' . $variables['field_name'];
}

function scratchpad_relations_preprocess_views_view_field(&$vars){
  /* if($vars['view']->name == 'species_relationships' && $vars['field']->field = 'field_ecological_relationship'){
     dpm($vars['field']);
     $vars['output'] = str_replace('<li>', '', $vars['output']);
     $vars['output'] = str_replace('</li>', '', $vars['output']);
    $vars['output'] = str_replace('<ul>', '', $vars['output']);
    $vars['output'] = str_replace('</ul>', '<br/>', $vars['output']);
  }*/
}
