(function($) {
  // Replaces the cluser point background image with a gradient color, as the PDF generated by PhantomJS
  // doesn't handle the background images well.
  Drupal.behaviors.scrachpads_citethispage_gmapagg = {
    attach: function(context, settings) {
      setTimeout(function() {
        var cluster_re = /markerclustererplus/;
        $('div.gm3-map-wrapper div', context).filter(function() {
          return cluster_re.test($(this).css('background-image'));
        }).each(function() {
          var height = $(this).height();
          var width = $(this).width();
          $(this).css('border-radius', height > width ? height : width);
          if (/m1/.test($(this).css('background-image'))) {
            // Blue
            $(this).css('background', '-webkit-radial-gradient(center, ellipse cover, rgba(75,160,229,1) 17%,rgba(75,160,229,0.59) 42%,rgba(167,216,244,0) 78%,rgba(170,218,244,0) 79%)');            
          } else if (/m2/.test($(this).css('background-image'))) {
            // Orange
            $(this).css('background', '-webkit-radial-gradient(center, ellipse cover, rgba(229,209,75,1) 17%,rgba(229,209,75,0.59) 42%,rgba(244,227,167,0) 78%,rgba(244,227,170,0) 79%)');
          } else {
            // Red
            $(this).css('background', '-webkit-radial-gradient(center, ellipse cover, rgba(255,57,43,1) 17%,rgba(255,57,43,0.59) 42%,rgba(255,154,157,0) 78%,rgba(255,157,160,0) 79%)');
          }
        });
      }, 1000);
    }
  }
})(jQuery);
