<?php
/*
 * Implement hook_disable() 
 * 
 * Ensure Forum module gets disabled when this one gets
 * disabled
 */
function scratchpads_forum_disable(){
  // We need to disable the modules once everything else has done. So we register
  // a shutdown function with arguments.
  drupal_register_shutdown_function('module_disable', array('forum'));
  drupal_register_shutdown_function('drupal_flush_all_caches');
}
