version: '2'

services:
  apache:
    container_name: scratchpads.apache
    # image: naturalhistorymuseum/scratchpads.apache
    build:
      context: ./docker/apache
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
      - solr
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - apache-files:/var/www/html/sites/default
    environment:
      - DEVELOPMENT_ENV=${DEVELOPMENT_ENV}
      - BASE_URL=${APACHE_BASE_URL}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=scratchpads.mysql
      - SOLR_HOSTNAME=scratchpads.solr
      - SOLR_CORE=scratchpads2
      - SMTP_FROM=${APACHE_SMTP_FROM}
      - SMTP_HOST=${APACHE_SMTP_HOST}
      - SMTP_PORT=${APACHE_SMTP_PORT}
      - SMTP_USER=${APACHE_SMTP_USER}
      - SMTP_PASSWORD=${APACHE_SMTP_PASSWORD}
      - SMTP_TLS=${APACHE_SMTP_TLS}
      - SMTP_AUTH=${APACHE_SMTP_AUTH}
      - SMTP_START_TLS=${APACHE_SMTP_START_TLS}
      - VARNISH_SECRET=${VARNISH_SECRET}
      - TAVERNA_AUTH_TOKEN=${APACHE_SCRATCHPADS_TAVERNA_AUTH_TOKEN}
      - APACHE_RUN_DIR=/var/run/apache2
      - APACHE_PID_FILE=/var/run/apache2/apache2.pid
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2
      - APACHE_PHP_MEMORY_LIMIT=${APACHE_PHP_MEMORY_LIMIT}
      - APACHE_PHP_UPLOAD_MAX_FILESIZE=${APACHE_PHP_UPLOAD_MAX_FILESIZE}
      - APACHE_PHP_POST_MAX_SIZE=${APACHE_PHP_POST_MAX_SIZE}
      - APACHE_PHP_XDEBUG_MODE=${APACHE_PHP_XDEBUG_MODE}
      - APACHE_PHP_XDEBUG_START_WITH_REQUEST=${APACHE_PHP_XDEBUG_START_WITH_REQUEST}
      - APACHE_PHP_XDEBUG_CLIENT_HOST=${APACHE_PHP_XDEBUG_CLIENT_HOST}
      - APACHE_PHP_MAX_INPUT_VARS=${APACHE_PHP_MAX_INPUT_VARS}
      - GITHUB_AUTH_KEY=${APACHE_GITHUB_AUTH_KEY}
      - GITHUB_REPOSITORY=${APACHE_GITHUB_REPOSITORY}
      - GBIF_REGISTRY_PASSWORD=${GBIF_REGISTRY_PASSWORD}
    logging:
      driver: json-file
      options:
          max-file: "5"
          max-size: "100m"

  mysql:
    container_name: scratchpads.mysql
    restart: always
    image: naturalhistorymuseum/scratchpads-mysql
    build:
      context: ./docker/mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    logging:
      driver: json-file
      options:
          max-file: "5"
          max-size: "100m"

  solr:
    container_name: scratchpads.solr
    restart: always
    # image: naturalhistorymuseum/scratchpads-solr
    build:
      context: ./docker/solr
    ports:
      - "8983:8983"
    expose:
      - 8983
    volumes:
      - solr-data:/var/lib/solr-undertow/solr-home/scratchpads2/data:rw
    environment:
      - SOLR_UNDERTOW_OPTS=-Xms${SOLR_JVM_MEMORY} -Xmx${SOLR_JVM_MEMORY} -XX:MaxPermSize=512m -XX:PermSize=256m
    logging:
      driver: json-file
      options:
          max-file: "5"
          max-size: "100m"

  varnish:
    restart: always
    container_name: scratchpads.varnish
    image: naturalhistorymuseum/scratchpads-varnish
    build:
      context: ./docker/varnish
    depends_on:
      - apache
    expose:
      - 6082
    ports:
      - "${VARNISH_PORT_EXPOSE}:${VARNISH_PORT}"
    environment:
      VARNISH_PORT: ${VARNISH_PORT}
      VARNISH_SECRET: ${VARNISH_SECRET}
      VARNISH_MEMORY: ${VARNISH_MEMORY}
    logging:
      driver: json-file
      options:
          max-file: "5"
          max-size: "100m"

volumes:
  apache-files:
  mysql-data:
  solr-data:
