<?php

/**
 * @file
 */
/**
 * Implement hook_theme().
 */
function scratchpads_user_theme(){
  return array(
    'scratchpads_user_register_form' => array(
      'render element' => 'form'
    )
  );
}

function scratchpads_user_menu_alter(&$items){
  // Example - disable the page at node/add
  $items['admin/people']['page callback'] = 'scratchpads_user_admin';
}

/**
 * Menu callback;
 * Replaces user_admin(list) function to allow for real user names / hiding dummy usernames
 */
function scratchpads_user_admin($callback_arg = ''){
  $op = isset($_POST['op']) ? $_POST['op'] : $callback_arg;
  switch($op){
    case t('Cancel'):
    case t('Create new account'):
    case 'create':
      $build['user_register'] = drupal_get_form('user_register_form');
      break;
    default:
      if(!empty($_POST['accounts']) && isset($_POST['operation']) && ($_POST['operation'] == 'cancel')){
        $build['user_multiple_cancel_confirm'] = drupal_get_form('user_multiple_cancel_confirm');
      }else{
        $build['user_filter_form'] = drupal_get_form('user_filter_form');
        $build['user_admin_account'] = drupal_get_form('scratchpads_user_admin_account');
      }
  }
  return $build;
}

function scratchpads_user_admin_account_submit($form, &$form_state){
  module_load_include('admin.inc', 'user');
  return user_admin_account_submit($form, $form_state);
}

function scratchpads_user_admin_account(){
  $header = array(
    'username' => array(
      'data' => t('Username'),
      'field' => 'u.name'
    ),
    'given_names' => array(
      'data' => t('Given names'),
      'field' => 'fgn.field_user_given_names_value'
    ),
    'family_name' => array(
      'data' => t('Family name'),
      'field' => 'fn.field_user_family_name_value'
    ),
    'status' => array(
      'data' => t('Status'),
      'field' => 'u.status'
    ),
    'roles' => array(
      'data' => t('Roles')
    ),
    'member_for' => array(
      'data' => t('Member for'),
      'field' => 'u.created',
      'sort' => 'desc'
    ),
    'access' => array(
      'data' => t('Last access'),
      'field' => 'u.access'
    ),
    'operations' => array(
      'data' => t('Operations')
    )
  );
  $query = db_select('users', 'u');
  $query->condition('u.uid', 0, '<>');
  $query->condition('u.uid', 1, '<>');
  user_build_filter_query($query);
  $count_query = clone $query;
  $count_query->addExpression('COUNT(u.uid)');
  $query = $query->extend('PagerDefault')->extend('TableSort');
  // Note, the Joins must appear after the "extend('PagerDefault') code
  // http://drupal.stackexchange.com/questions/36907/pager-query-with-join
  $query->leftJoin('field_revision_field_user_family_name', 'fn', 'u.uid = fn.revision_id');
  $query->addField('fn', 'field_user_family_name_value', 'family_name');
  $query->leftJoin('field_revision_field_user_given_names', 'fgn', 'u.uid = fgn.revision_id');
  $query->addField('fgn', 'field_user_given_names_value', 'given_names');
  $query->fields('u', array(
    'uid',
    'name',
    'status',
    'created',
    'access',
    'pass'
  ));
  $query->limit(50);
  $query->orderByHeader($header);
  $query->setCountQuery($count_query);
  $result = $query->execute();
  $form['options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Update options'),
    '#attributes' => array(
      'class' => array(
        'container-inline'
      )
    )
  );
  $options = array();
  foreach(module_invoke_all('user_operations') as $operation => $array){
    $options[$operation] = $array['label'];
  }
  $form['options']['operation'] = array(
    '#type' => 'select',
    '#title' => t('Operation'),
    '#title_display' => 'invisible',
    '#options' => $options,
    '#default_value' => 'unblock'
  );
  $options = array();
  $form['options']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update')
  );
  $destination = drupal_get_destination();
  $status = array(
    t('blocked'),
    t('active')
  );
  $roles = array_map('check_plain', user_roles(TRUE));
  $accounts = array();
  foreach($result as $account){
    $users_roles = array();
    $roles_result = db_query('SELECT rid FROM {users_roles} WHERE uid = :uid', array(
      ':uid' => $account->uid
    ));
    foreach($roles_result as $user_role){
      $users_roles[] = $roles[$user_role->rid];
    }
    asort($users_roles);
    if(empty($account->pass)){
      $username = '';
    }else{
      $username = theme('username', array(
        'account' => $account
      ));
    }
    $options[$account->uid] = array(
      'username' => $username,
      'given_names' => $account->given_names,
      'family_name' => $account->family_name,
      'status' => $status[$account->status],
      'roles' => theme('item_list', array(
        'items' => $users_roles
      )),
      'member_for' => format_interval(REQUEST_TIME - $account->created),
      'access' => $account->access ? t('@time ago', array(
        '@time' => format_interval(REQUEST_TIME - $account->access)
      )) : t('never'),
      'operations' => array(
        'data' => array(
          '#type' => 'link',
          '#title' => t('edit'),
          '#href' => "user/$account->uid/edit",
          '#options' => array(
            'query' => $destination
          )
        )
      )
    );
  }
  $form['accounts'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $options,
    '#empty' => t('No people available.')
  );
  $form['pager'] = array(
    '#markup' => theme('pager')
  );
  return $form;
}

/**
 * 
 * Implement hook_ENTITY_TYPE_load()
 */
function scratchpads_user_user_load($entities){
  // For entitites with a dummy username, use the name/surname
  foreach($entities as $entity_id => $entity){
    if($entity->uid && empty($entity->pass)){
      // Is this user just a stub - cannot login
      $entities[$entity_id]->stub_user = true;
      // Following edited as it throws up an error on install with UID 1.
      $new_name = trim((isset($entity->field_user_given_names[LANGUAGE_NONE]) ? $entity->field_user_given_names[LANGUAGE_NONE][0]['safe_value'] : '') . ' ' . (isset($entity->field_user_family_name[LANGUAGE_NONE]) ? $entity->field_user_family_name[LANGUAGE_NONE][0]['safe_value'] : ''));
      if($new_name){
        $entities[$entity_id]->name = $new_name;
      }
    }
  }
  return $entities;
}

/**
 * Helper function to replace a submit handler in a form with any other number of handlers
 * 
 */
function _scratchpads_user_replace_submit_handler(&$form, $origin_handler, $handlers){
  if(!isset($form['actions']['submit']['#submit'])){
    $form['actions']['submit']['#submit'] = $handlers;
  }else{
    $pos = array_search($origin_handler, $form['actions']['submit']['#submit']);
    if($pos === FALSE){
      $form['actions']['submit']['#submit'] = array_merge($handlers, $form['actions']['submit']['#submit']);
    }else{
      array_splice($form['actions']['submit']['#submit'], $pos, 1, $handlers);
    }
  }
}

/**
 * Implement hook_form_FORM_ID_alter().
 */
function scratchpads_user_form_user_register_form_alter(&$form, &$form_state){
  _scratchpads_user_form_alter($form, $form_state);
  if(count($form_state['input']) && !isset($form_state['input']['create_user_account'])){
    $handlers = array(
      'scratchpads_user_register_form_pre_submit',
      'user_register_submit',
      'scratchpads_user_register_form_post_submit'
    );
    _scratchpads_user_replace_submit_handler($form, 'user_register_submit', $handlers);
  }
  array_unshift($form['#validate'], 'scratchpads_user_user_register_validate');
}

/**
 * Validate the user register form so that we can add an email address if we are
 * not allowing login!
 */
function scratchpads_user_user_register_validate($form, &$form_state){
  if(!$form_state['values']['create_user_account']){
    $errors = form_get_errors();
    if(is_array($errors) && isset($errors['mail'])){
      unset($errors['mail']);
      form_clear_error();
      foreach($errors as $key => $msg){
        form_set_error($key, $msg);
      }
    }
    global $base_url;
    $url = parse_url($base_url);
    $form_state['values']['mail'] = uniqid() . '@' . $url['host'];
  }
}

/**
 * Implements hook_module_implements_alter()
 */
function scratchpads_user_module_implements_alter(&$imps, $hook){
  if($hook == 'form_alter'){
    $this_module = $imps['scratchpads_user'];
    unset($imps['scratchpads_user']);
    $imps['scratchpads_user'] = $this_module;
  }
}

/**
 * Implement hook_form_FORM_ID_alter().
 */
function scratchpads_user_form_user_profile_form_alter(&$form, &$form_state){
  global $user;
  _scratchpads_user_form_alter($form, $form_state);
  if(isset($form['#user']->stub_user)){
    $form['account']['name']['#default_value'] = '';
    $form['create_user_account']['#default_value'] = 0;
    // Get rid of the crap that we don't need (biblio, etc).
    unset($form['biblio_fieldset']);
    unset($form['overlay_control']);
    unset($form['timezone']);
    unset($form['comment_notify_settings']);
    unset($form['contact']);
    unset($form['legal']);
  }else{
    $form['create_user_account']['#default_value'] = 1;
    if($user->uid == 1){
      $form['create_user_account']['#disabled'] = true;
      if(count($form_state['input'])){
        $form_state['input']['create_user_account'] = 1;
      }
    }
  }
  if(count($form_state['input']) && !isset($form_state['input']['create_user_account'])){
    $handlers = array(
      'scratchpads_user_register_form_pre_submit_edit',
      'scratchpads_user_register_form_post_submit_clear_error'
    );
    _scratchpads_user_replace_submit_handler($form, 'user_register_submit', $handlers);
  }
}

/**
 * 
 * helper function - make alterations to both the user_profile_form() & user_register_form() forms
 * @param array $form
 * @param array $form_state
 */
function _scratchpads_user_form_alter(&$form, &$form_state){
  global $user;
  $form['account']['#type'] = 'fieldset';
  $form['account']['#title'] = t('User account settings');
  if($user->uid > 0){
    $form['account']['#states'] = array(
      // Hide the settings when the cancel notify checkbox is disabled.
      'invisible' => array(
        'input[name="create_user_account"]' => array(
          'checked' => FALSE
        )
      )
    );
    $form['create_user_account'] = array(
      '#type' => 'checkbox',
      '#title' => t('Allow user login?'),
      '#description' => t("Do you want to create a user account for this user so they can log into the website?"),
      '#default_value' => 1,
      '#disabled' => ($form['#user']->uid ? 1 : 0)
    );
  }else{
    $form['create_user_account'] = array(
      '#type' => 'hidden',
      '#value' => 1
    );
  }
  $form['#fields'] = field_info_instances($form['#entity_type'], $form['#bundle']);
  // Add the theme function to make this form look better
  array_unshift($form['#theme'], 'scratchpads_user_register_form');
  // If the user isn't creating a user account, limit the validation errors to email & extra fields
  if(count($form_state['input']) && !isset($form_state['input']['create_user_account']) && (!$form['#user']->uid || $form_state['input']['name'] == '')){
    $form['actions']['submit']['#limit_validation_errors'] = array(
      array(
        'mail'
      ),
      array(
        'parent_build_cache_id'
      )
    );
    foreach($form['#fields'] as $field_name => $field){
      $form['actions']['submit']['#limit_validation_errors'][] = array(
        $field_name
      );
    }
  }
}

/**
 * Submit function called before user_register_submit()
 * Used to manipulate the values before the user is saved
 * @param array $form
 * @param array $form_state
 */
function scratchpads_user_register_form_pre_submit($form, &$form_state){
  $form_state['values']['administer_users'] = 1;
  $form_state['values']['name'] = uniqid();
}

/**
 * Similar to above, but just setting administer_users and notify.
 */
function scratchpads_user_register_form_pre_submit_edit($form, &$form_state){

  $account = $form_state['user'];
  $category = $form['#user_category'];
  // Remove unneeded values.
  form_state_values_clean($form_state);
  
  // Before updating the account entity, keep an unchanged copy for use with
  // user_save() later. This is necessary for modules implementing the user
  // hooks to be able to react on changes by comparing the values of $account
  // and $edit.
  $account_unchanged = clone $account;
  
  entity_form_submit_build_entity('user', $account, $form, $form_state);
  
  // Populate $edit with the properties of $account, which have been edited on
  // this form by taking over all values, which appear in the form values too.
  $edit = array_intersect_key((array) $account, $form_state['values']);
  
  user_save($account_unchanged, $edit, $category);
  $form_state['values']['uid'] = $account->uid;
  
  if ($category == 'account' && !empty($edit['pass'])) {
    // Remove the password reset tag since a new password was saved.
    unset($_SESSION['pass_reset_'. $account->uid]);
  }
  // Clear the page cache because pages can contain usernames and/or profile information:
  cache_clear_all();
  
  drupal_set_message(t('The changes have been saved.'));
  return;
  // Remove unneeded values.
  form_state_values_clean($form_state);
  $account = $form['#user'];
  entity_form_submit_build_entity('user', $account, $form, $form_state);
  if(!variable_get('user_email_verification', TRUE) || $form_state['values']['administer_users']){
    $pass = $form_state['values']['pass'];
  }else{
    $pass = user_password();
  }
  $form_state['values']['pass'] = $pass;
  // Populate $edit with the properties of $account, which have been edited on
  // this form by taking over all values, which appear in the form values too.
  $edit = array_intersect_key((array)$account, $form_state['values']);
  $account = user_save($account, $edit);
}

/**
 * Submit function simply to clear the errors displayed in user_register_submit.
 */
function scratchpads_user_register_form_post_submit_clear_error($form, &$form_state){
  drupal_get_messages('error');
  if(isset($form_state['values']['uid']) && $form_state['values']['uid']){
    $form_state['redirect'] = 'user/' . $form_state['values']['uid'];
  }
}

/**
 * Add the user/register as an admin path (the registration form looks 100x
 * better in an overlay).
 */
function scratchpads_user_admin_paths(){
  return array(
    'user/register' => TRUE
  );
}

/**
 * Submit function called after user_register_submit()
 * Used to manipulate the message displayed to the user
 * @param array $form
 * @param array $form_state
 */
function scratchpads_user_register_form_post_submit($form, &$form_state){
  // Reset the messages
  drupal_get_messages('status');
  // Reset the error messages, as the following error is displayed:
  // Notice: Undefined index: pass in user_register_submit() (line 3752 of /home/simor/Zend/workspaces/DefaultWorkspace7/Scratchpads-2.0/modules/user/user.module).
  drupal_get_messages('error');
  drupal_set_message(t('Created a new profile for @user_title @user_given_name @user_family_name.', array(
    '@user_title' => $form_state['values']['field_user_title'][LANGUAGE_NONE][0]['value'],
    '@user_given_name' => $form_state['values']['field_user_given_names'][LANGUAGE_NONE][0]['value'],
    '@user_family_name' => $form_state['values']['field_user_family_name'][LANGUAGE_NONE][0]['value']
  )));
  // Give a warning that no user account was created
  drupal_set_message('No user account was created so this person will not be able to log into the website!', 'warning');
  // Ensure that no password is set
  $form['#user']->pass = '';
  user_save($form['#user']);
}

function _scratchpads_user_register_field_sort($a, $b){
  return $a['widget']['weight'] >= $b['widget']['weight'];
}

function theme_scratchpads_user_register_form($variables){
  //print_r($variables['form']);exit;
  // Add CSS
  drupal_add_css(drupal_get_path('module', 'scratchpads_user') . '/css/scratchpads_user.css');
  $output = '<div class="clearfix"><div class="scratchpads-user-left"><div>';
  // Add the email field
  $fields = $variables['form']['#fields'];
  uasort($fields, '_scratchpads_user_register_field_sort');
  //print_r($fields);exit;
  $field_names = array_keys($fields);
  // And then any field api fields
  foreach($field_names as $field_name){
    $output .= drupal_render($variables['form'][$field_name]);
  }
  $output .= '</div></div><div class="scratchpads-user-right clearfix"><div>';
  $output .= drupal_render($variables['form']['create_user_account']);
  // And then the rest of the form
  $actions = $variables['form']['actions'];
  unset($variables['form']['actions']);
  $output .= drupal_render_children($variables['form']);
  $output .= drupal_render($variables['form']['account']['mail']);
  $output .= '</div></div></div>';
  $output .= drupal_render($actions);
  return $output;
}