<?php

/**
 * Simple Google Maps v3 API module file.
 * 
 */
/**
 * Implementation of hook_library().
 * 
 * Note, the sensor option could be set to true here to allow for maps to have 
 * the sensor enabled (useful perhaps on mobile devices, or shopping sites).
 */
function gm3_library(){
  return array(
    'gm3' => array(
      'title' => t('Google Maps Javascript API V3'),
      'website' => 'http://code.google.com/apis/maps/documentation/javascript/',
      'version' => '3',
      'js' => array(
        array(
          'data' => drupal_get_path('module', 'gm3') . '/js/gm3.js'
        ),
        array(
          'data' => 'http://maps.googleapis.com/maps/api/js?sensor=false',
          'options' => 'external'
        )
      ),
      'css' => array(
        array(
          'data' => 'http://code.google.com/apis/maps/documentation/javascript/examples/default.css'
        )
      )
    ),
    'gm3.geometry' => array(
      'title' => t('Google Maps Javascript API V3: Geometry library'),
      'website' => 'http://code.google.com/apis/maps/documentation/javascript/geometry.html',
      'version' => '3',
      'js' => array(
        array(
          'data' => 'http://maps.googleapis.com/maps/api/js?libraries=geometry&sensor=false',
          'options' => 'external'
        )
      )
    )
  );
}

/**
 * Callback to add a Google map to a specific element ID on the page.
 */
function gm3_add($id, $settings = array()){
  drupal_add_library('gm3', 'gm3');
  $settings = array_merge($settings, array(
    'width' => '100%',
    'height' => '500px',
    'center' => array(
      'latitude' => 52,
      'longitude' => 0
    ),
    /*'backgroundColor' => 'white',
    'disableDefaultUI' => FALSE,
    'disableDoubleClickZoom' => FALSE,
    'draggable' => TRUE,
    'graggableCursor' => 'move',
    'draggingCursor' => 'move',
    'heading' => 0,
    'keyboardShortcuts' => TRUE,
    'mapTypeControl' => TRUE,
    'mapTypeControlOptions' => array(
      'mapTypeIds' => array(
        'SATELLITE'
      ),
      'position' => 'TOP_RIGHT', // http://code.google.com/apis/maps/documentation/javascript/reference.html#ControlPosition
      'style' => 'DEFAULT' // http://code.google.com/apis/maps/documentation/javascript/reference.html#MapTypeControlStyle
    ),*/
    'mapTypeId' => 'TERRAIN', // SATELLITE, TERRAIN, ROADMAP, HYBRID
    /*'zoom' => 4,
    'maxZoom' => null,
    'minZoom' => null,
    'noClear' => FALSE,
    'overviewMapControl' => FALSE*/
  ));
  drupal_add_js(array(
    'gm3' => array(
      'maps' => array(
        array(
          'id' => $id,
          'settings' => $settings
        )
      )
    )
  ), 'setting');
}

/**
 * Implementation of hook_init().
 * 
 * FIXME - This is purely for testing, and nothing else.
 */
function gm3_init(){
  gm3_add('first-time');
}