<?php

/**
 * Implements hook_block_info().
 */
function ncbi_block_info(){
  return array(
    'default' => array(
      'info' => t('NCBI Species Page Block'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'pages' => 'taxonomy/term/*/descriptions',
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'status' => 1,
      'region' => 'content'
    )
  );
}

/**
 * Implements hook_block_view().
 */
function ncbi_block_view($delta = ''){
  switch($delta){
    default:
      // We load the term from the menu
      $term = menu_get_object('taxonomy_term', 2);
      if($term){
        $items = _ncbi_get_data($term);
        foreach($items as $key => $item){
          $items[$key] = array(
            'data' => $item,
            'style' => 'margin-left:0'
          );
        }
        if(count($items)){return array(
            'subject' => t('NCBI'),
            'content' => array(
              'block' => array(
                '#theme' => 'item_list',
                '#items' => $items,
                '#attributes' => array(
                  'style' => 'padding-left:0'
                )
              )
            )
          );}
      }
  }
  return array();
}

/**
 * Helper function to get some data from NCBI.
 */
function _ncbi_get_data($term){
  $items = array();
  $esearch_xml = file_get_contents('http://fencedine.myspecies.info/?url=' . urlencode('http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=taxonomy&term=' . urlencode($term->name)));
  if($esearch_xml){
    $esearch_results = new SimpleXMLElement($esearch_xml);
  }
  if($esearch_results){
    if($esearch_results->IdList->Id){
      foreach($esearch_results->IdList->Id as $id){
        $dom = DOMDocument::loadHTMLFile('http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=' . $id);
        $tables = $dom->getElementsByTagName('table');
        foreach($tables as $table){
          if($table->getAttribute('align') == 'right'){
            $trs = $table->getElementsByTagName('tr');
            $rows = array();
            $row_num = 0;
            foreach($trs as $tr){
              if($row_num > 0){
                $tds = $tr->getElementsByTagName('td');
                $row = array();
                foreach($tds as $td){
                  $html = preg_replace('/\xC2\xA0/', ' ', $dom->saveXML($td));
                  $html = str_replace('href="', 'target="_blank" href="http://www.ncbi.nlm.nih.gov', $html);
                  $row[] = filter_xss($html);
                }
                $rows[] = $row;
              }
              $row_num++;
            }
          }
        }
        $headers = array_shift($rows);
        $elink_request = 'http://fencedine.myspecies.info/?url=' . urlencode('http://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=taxonomy&db=all&id=' . $id . '&cmd=llinks');
        $elink_request_xml = file_get_contents($elink_request);
        if($elink_request_xml){
          $elinks = new SimpleXMLElement($elink_request_xml);
          $links = array();
          foreach($elinks->LinkSet->IdUrlList->IdUrlSet->ObjUrl as $link){
            if($link->LinkName){
              if($link->Provider->NameAbbr == 'taxresource'){
                $name = 'GBIF bookmark: ' . $link->LinkName;
              }else{
                $name = $link->Provider->NameAbbr . ': ' . $link->LinkName;
              }
              $title = $link->Provider->Name . ': ' . $link->LinkName;
            }else{
              $name = $link->Provider->Name;
              $title = $name;
            }
            $links[] = array(
              'data' => '<a href="' . $link->Url . '" title="' . $title . '">' . $name . '</a>',
              'style' => 'list-style:disc;padding-bottom:3px;'
            );
          }
        }
        $items[] = theme('table', array(
          'header' => $headers,
          'rows' => $rows
        )) . theme('item_list', array(
          'items' => $links,
          'attributes' => array(
            'style' => 'display:none'
          ),
          'title' => '<a onclick="jQuery(this).parent().next().toggle();return false" href="#">' . t('External links') . '</a>'
        ));
      }
    }
  }
  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function ncbi_form_block_admin_configure_alter(&$form, &$form_state, $form_id){
  if($form['module']['#value'] == 'ncbi'){
    // Prevent editing of this block.
    if(!user_access('scratchpad team')){
      drupal_set_message(t('You may not edit the IUCN block'));
      drupal_goto();
    }
  }
}

/**
 * Implements hook_contextual_links_view_alter().
 */
function ncbi_contextual_links_view_alter(&$element, $items){
  if(@isset($element['#contextual_links']['block'][1][0]) && $element['#contextual_links']['block'][1][0] == 'ncbi'){
    $element = array();
  }
}