<?php

/**
 * Implementation of hook_image_default_styles().
 */
function scratchpads_image_styles_image_default_styles(){
  $styles = array();
  // Exported image style: sp_square_thumbnail
  $styles['sp_square_thumbnail'] = array(
    'name' => 'sp_square_thumbnail',
    'effects' => array(
      1 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => '100',
          'height' => '100'
        ),
        'weight' => '1'
      )
    )
  );
  return $styles;
}
