<?php
define('SCRATCHPADS_ORGANIZATION', '315b3c03-4a0a-424e-83a5-d25aa748e666');
define('SCRATCHPADS_NHM_INSTALLATION', '69818b49-38c9-41ad-b504-e5cd53dff238');

/**
 * Implements hook_cron().
 */
function scratchpads_gbif_registry_client_cron(){
  // Go no further if we're not the right profile or we updated less than a week
  // ago.
  if(in_array(variable_get('install_profile', ''), scratchpads_gbif_registry_client_profiles()) && variable_get('scratchpads_gbif_registry_client_last_update', 0) + 604800 < time()){
    // Once a week we update the information that GBIF holds about us.
    $registry = GBIFRegistry::singleton();
    if(($uuid = variable_get('scratchpads_gbif_registry_client_uuid', FALSE)) != FALSE){
      $dataset = new GBIF\Dataset($uuid);
    }else{
      // We need to create a new Dataset for the Scratchpad
      // organization.
      $homepage = url('', array(
        'absolute' => TRUE
      ));
      $site_name = variable_get('site_name', FALSE);
      $dataset = new GBIF\Dataset(array(
        'installationKey' => variable_get('scratchpads_gbif_registry_client_scratchpads_nhm_installation', SCRATCHPADS_NHM_INSTALLATION),
        'publishingOrganizationKey' => variable_get('scratchpads_gbif_registry_client_scratchpads_organization', SCRATCHPADS_ORGANIZATION),
        'external' => FALSE,
        'numConstituents' => 0,
        'type' => 'CHECKLIST',
        'title' => 'Checklist ' . (module_exists('darwincore') ? 'and specimen ' : '') . 'records from the Scratchpad "' . ($site_name ? $site_name : $homepage) . '"',
        'description' => variable_get('scratchpads_gbif_registry_client_description', ''),
        'language' => 'eng',
        'homepage' => $homepage,
        'citation' => array(
          'text' => 'Specimen/Occurrence records from the Scratchpad "' . ($site_name ? $site_name : $homepage) . '"' . ($site_name ? " $homepage" : '')
        ),
        'lockedForAutoUpdate' => FALSE,
        'tags' => array()
      ));
      $dataset->save();
      variable_set('scratchpads_gbif_registry_client_uuid', $dataset->getKey());
      // Add a technical contact, which is the scratchpads team.
      $dataset->addContact(array(
        'type' => 'TECHNICAL_POINT_OF_CONTACT',
        'primary' => false,
        'firstName' => 'Scratchpads',
        'lastName' => 'Team',
        'email' => array(
          'scratchpads@nhm.ac.uk'
        ),
        'phone' => array(
          '+44 20 7942 6279',
          '+44 20 7942 5127'
        ),
        'homepage' => array(
          'http://scratchpads.eu/'
        ),
        'position' => array(
          'Development Team',
          'Support Team'
        ),
        'address' => array(
          'The Natural History Museum, Cromwell Road, London, SW7 5BD, UK'
        )
      ));
    }
    $query = db_select('users', 'u')->fields('u', array(
      'uid'
    ));
    // And add all maintainers as "contacts"
    $query->innerJoin('users_roles', 'ur', 'u.uid = ur.uid');
    $query->innerJoin('role', 'r', 'ur.rid = r.rid');
    $query->condition('r.name', 'maintainer');
    $uids = $query->execute()->fetchCol();
    $users = user_load_multiple($uids);
    foreach($dataset->getContacts() as $contact){
      $contact = $contact->getAsArray();
      foreach($users as $key => $user){
        if($contact['email'][0] == $user->mail){
          unset($users[$key]);
          break;
        }
      }
    }
    foreach($users as $user){
      $dataset->addContact(array(
        'type' => 'POINT_OF_CONTACT',
        'primary' => FALSE,
        'firstName' => isset($user->field_user_given_names[LANGUAGE_NONE][0]['value']) ? $user->field_user_given_names[LANGUAGE_NONE][0]['value'] : '',
        'lastName' => isset($user->field_user_family_name[LANGUAGE_NONE][0]['value']) ? $user->field_user_family_name[LANGUAGE_NONE][0]['value'] : '',
        'email' => array(
          $user->mail
        ),
        'position' => array(
          'Scratchpads Maintainer'
        )
      ));
    }
    // Get a list of endpoints that we need to register for this installation.
    $endpoints = module_invoke_all('gbif_registry_endpoints');
    foreach($dataset->getEndpoints() as $endpoint){
      unset($endpoints[$endpoint->getURL()]);
    }
    foreach($endpoints as $endpoint){
      $dataset->addEndpoint($endpoint);
    }
    if(variable_get('scratchpads_gbif_registry_client_uuid', FALSE)){
      variable_set('scratchpads_gbif_registry_client_last_update', time());
    }
  }
}

/**
 * Helper function to return an array of profiles that should report back to
 * GBIF.
 */
function scratchpads_gbif_registry_client_profiles(){
  return array(
    'scratchpad_2',
    'emonocot_2',
    'scratchpad_2_migrate',
    'emonocot_2_migrate'
  );
}