<?php

function scratchpad_relations_itis_form_taxonomy_form_vocabulary_alter(&$form, &$form_state, $form_id){
  $form['#submit'][] = 'scratchpad_relations_itis_taxonomy_form_vocabulary_submit';
}

/**
 * Submit function to alter a vocabulary.
 */
function scratchpad_relations_itis_taxonomy_form_vocabulary_submit($form, &$form_state){
  if(!isset($form_state['confirm_delete']) && $form_state['values']['biological_classification']){
    scratchpad_relations_itis_create_vocabulary($form_state['vocabulary']);
  }
}

function scratchpad_relations_itis_create_vocabulary($vocabulary){
  // Add all the required fields to this vocabulary.
  module_load_include('fields.inc', 'scratchpad_relations_itis');
  // Associate all the other fields with this instance.
  foreach(scratchpad_relations_itis_fields($vocabulary->vid) as $field){
    // Create the field if it hasn't already been created.
    if(!field_info_field($field['field_config']['field_name'])){
      field_create_field($field['field_config']);
    }
    $field['field_instance']['bundle'] = $vocabulary->machine_name;
    field_create_instance($field['field_instance']);
  }
  foreach(scratchpad_relations_itis_groups($vocabulary->vid) as $group){
    $group['bundle'] = $vocabulary->machine_name;
    $group['identifier'] = "{$group['group_name']}|{$group['bundle']}";
    $group = (object)$group;
    field_group_group_save($group);
  }
  //Now add the new group to the groups in itis_term
  module_load_include('fields.inc', 'itis_term');
  foreach(itis_term_groups($vocabulary->machine_name) as $itis_group){
    foreach(scratchpad_relations_itis_groups($vocabulary->vid) as $rel_group){
      if($rel_group['parent_name'] == $itis_group['group_name']){
        $group = field_group_load_field_group($itis_group['group_name'], 'taxonomy_term', $vocabulary->machine_name, 'form');
        $group->children[] = $rel_group['group_name'];
        field_group_group_save($group);
      }
    }
  }
}