<?php

function hortus_module_implements_alter(&$implementations, $hook) {
  if (isset($implementations['scratchpads_file_colorboxed'])) {
    unset($implementations['scratchpads_file_colorboxed']);
  }
}

function hortus_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full') {
    drupal_add_css(drupal_get_path('module', 'hortus').'/css/hortus.css', array('group' => CSS_DEFAULT, 'every_page => TRUE'));
  }
}