<?php

/*
 * Ideally the field definitions on which this module works (tables, references, figures) should be defined here.
 * However Features does not currently allow to separate the field definition from the field instance, making
 * this impossible.
 * 
 * There is work in progress to address this in Feature: http://drupal.org/node/1064472
 * 
 * In the mean time this means that the publication_html_format module cannot work unless the pensoft_publication module
 * is also enabled.
 */
