<?php

include_once('darwincore.features.inc');

/**
 * @file
 * 
 * This is the main module file for the Darwincore module.  This provides the 
 * Specimen and Location content types.
 * 
 * Changes from Drupal 6.x
 */
/**
 * Implementation of hook_help
function darwincore_help($path, $arg){
  switch($path){
    case 'node/add/specimen_observation':
      return t('');// FIXME - Add help text here.
    case 'node/add/darwincorelocation':
      return t('');// FIXME - Add help text here.
  }
}
 */

/**
 * 
 */