<?php
define("MIGRATE_NONE", 0);
define("MIGRATE_ALL", 1);
define("MIGRATE_CONTENT", 2);
/**
 * Add the database connection.
 * 
 * We're not adding the additional connection into the settings.php file as that
 * file is managed by Aegir.  Instead, every new site that is going to become
 * an "old" site will have an additional settings file in its files folder.
 * Simply including that file will add the additional database connection.  The
 * file should look like:
//----------
<?php
Database::addConnectionInfo('scratchpad_1', 'default', array(
  'database' => 'scratchpad_1_database',
  'username' => 'scratchpad_1_user',
  'password' => 'scratchpad_1_database_password',
  'host' => 'localhost',
  'port' => '',
  'driver' => 'mysql',
  'prefix' => ''
));
//----------
 */

require_once (conf_path() . '/files/scratchpad_1_database.php');

function scratchpads_migrate_menu(){
  $items['mig'] = array(
    'title' => 'Migrate',
    'page callback' => 'scratchpads_migrate_page',
    'access arguments' => array(
      'access content'
    ),
    'type' => MENU_SUGGESTED_ITEM
  );
  return $items;
}

function scratchpads_migrate_page(){
  return $x;
}

/**
 * Implements hook_flush_caches().
 */
function scratchpads_migrate_flush_caches(){
  scratchpads_migrate_register_migrations();
}

/**
 * Implements hook_migrate_api().
 */
function scratchpads_migrate_migrate_api(){
  return array(
    'api' => 2
  );
}

/**
 * Register all of the migrations for this module.
 */
function scratchpads_migrate_register_migrations(){
  // The database connection to the Scratchpad 1 site.
  $common_arguments = array(
    'source_connection' => 'scratchpad_1',
    'source_version' => 6
  );
  /*********************************************************************************************
   * ContentTypes
   ********************************************************************************************/
  $arguments = $common_arguments + array(
    'description' => t('Migration of content types from Drupal 6'),
    'machine_name' => 'ContentType'
  );
  Migration::registerMigration('DrupalContentType6Migration', $arguments['machine_name'], $arguments);
  /*********************************************************************************************
   * Vocabularies
   ********************************************************************************************/
  $arguments = $common_arguments + array(
    'description' => t('Migration of vocabularies from Drupal 6'),
    'machine_name' => 'Vocabulary'
  );
  Migration::registerMigration('DrupalVocabulary6Migration', $arguments['machine_name'], $arguments);
  /*********************************************************************************************
   * Fields
   ********************************************************************************************/
  // The description and the migration machine name are also required arguments,
  // which will be unique for each migration you register.
  $arguments = $common_arguments + array(
    'description' => t('Migration of fields from Drupal 6'),
    'machine_name' => 'Field',
    'dependencies' => array(
      'ContentType'
    )
  );
  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalField6Migration', $arguments['machine_name'], $arguments);
  /*********************************************************************************************
   * Body fields
   ********************************************************************************************/
  $arguments = $common_arguments + array(
    'description' => t('Migration of body fields from Drupal 6'),
    'machine_name' => 'FieldBody',
    'dependencies' => array(
      'ContentType'
    )
  );
  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalFieldBody6Migration', $arguments['machine_name'], $arguments);
  /*********************************************************************************************
   * Taxonomy fields
   ********************************************************************************************/
  $arguments = $common_arguments + array(
    'description' => t('Migration of taxonomy fields from Drupal 6'),
    'machine_name' => 'FieldTaxonomy',
    'dependencies' => array(
      'ContentType',
      'Vocabulary'
    )
  );
  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalFieldTaxonomy6Migration', $arguments['machine_name'], $arguments);
  /*********************************************************************************************
   * Field groups
   ********************************************************************************************/
  $arguments = $common_arguments + array(
    'description' => t('Migration of field groups from Drupal 6'),
    'machine_name' => 'FieldGroup',
    'dependencies' => array(
      'Field',
      'FieldBody',
      'FieldTaxonomy'
    )
  );
  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalFieldGroup6Migration', $arguments['machine_name'], $arguments);
  /*********************************************************************************************
   * User
   ********************************************************************************************/
  $arguments = $common_arguments + array(
    'description' => t('Migration of users from Drupal 6'),
    'machine_name' => 'User'
  );
  Migration::registerMigration('ScratchpadsUser6Migration', $arguments['machine_name'], $arguments);
  /*********************************************************************************************
   * Files
   ********************************************************************************************/
  $arguments = $common_arguments + array(
    'description' => t('Migration of files from Drupal 6'),
    'machine_name' => 'File',
    'dependencies' => array(
      'User'
    )
  );
  Migration::registerMigration('DrupalFile6Migration', $arguments['machine_name'], $arguments);
  // Define node arguments here so all term migrations can be added as depenencies
  $common_node_arguments = $common_arguments + array(
    'user_migration' => 'User',
    'dependencies' => array( // Content types & fields must be migrated first 
      'ContentType',
      'Field',
      'FieldBody',
      'FieldTaxonomy',
      'FieldGroup',
      'User',
      'Vocabulary'
    )
  );
  /*********************************************************************************************
   * Terms
   ********************************************************************************************/
  $common_term_arguments = $common_arguments + array(
    'dependencies' => array( // Content types & fields must be migrated first 
      'Vocabulary'
    )
  );
  // Get vocabularies to register the term migrations
  $query = Database::getConnection('default', 'scratchpad_1')->select('vocabulary', 'v');
  $query->fields('v', array(
    'vid',
    'name'
  ));
  $query->condition('module', array(
    'forum',
    'scratchpadify',
    'taxonomy'
  ), 'IN');
  $query->condition('name', 'Image Galleries', '!=');
  $vocabularies = $query->execute();
  foreach($vocabularies as $vocabulary){
    $arguments = array(
      'class_name' => ScratchpadTerm6Migration,
      'description' => t('Migration of %name terms from Drupal 6', array(
        '%name' => $vocabulary->name
      )),
      'machine_name' => scratchpads_migrate_term_machine_name($vocabulary->name),
      'source_vocabulary' => $vocabulary->vid,
      'destination_vocabulary' => $vocabulary->vid
    );
    $arguments = array_merge_recursive($arguments, $common_term_arguments);
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'], $arguments);
    $common_node_arguments['dependencies'][] = $arguments['machine_name'];
  }
  /*********************************************************************************************
   * Nodes
   ********************************************************************************************/
  // Create the organic groups migration class seperately so other nodes can be made dependent
  $arguments = array(
    'class_name' => 'ScratchpadsNodeOrganicGroup6Migration',
    'description' => t('Migration of %type nodes from Drupal 6', array(
      '%type' => 'group'
    )),
    'machine_name' => 'OrganicGroup',
    'source_type' => 'group',
    'destination_type' => 'group'
  );
  $arguments = array_merge_recursive($arguments, $common_node_arguments);
  Migration::registerMigration($arguments['class_name'], $arguments['machine_name'], $arguments);
  $common_node_arguments['dependencies'][] = 'OrganicGroup';
  $mappings = scratchpads_migrate_type_mappings();
  // Get unmapped node types (custom content types on site)
  $query = Database::getConnection('default', 'scratchpad_1')->select('node_type', 'nt');
  $query->addField('nt', 'type');
  $query->condition('nt.type', array_keys($mappings), 'NOT IN');
  $result = $query->execute();
  foreach($result as $unmapped_node_type){
    $mappings[$unmapped_node_type->type] = MIGRATE_ALL;
  }
  foreach($mappings as $type => $mapping){
    // Skip if we don't want to migrate this content type
    if($mapping == MIGRATE_NONE){
      continue;
    }
    if(is_array($mapping)){
      if(isset($mapping['entity_type']) && $mapping['entity_type'] != 'node'){
        // Only do nodes at the moment
        continue;
      }
      if(isset($mapping['bundle'])){
        $destination_type = $mapping['bundle'];
      }
    }else{
      $destination_type = $type;
    }
    // Allow individual node type handlers
    $class_name = 'ScratchpadsNode' . ucfirst($type) . '6Migration';
    if(!class_exists($class_name)){
      $class_name = 'ScratchpadsNode6Migration';
    }
    // Create the arguments array from the mapping
    $arguments = array(
      'class_name' => $class_name,
      'description' => t('Migration of %type nodes from Drupal 6', array(
        '%type' => $type
      )),
      'machine_name' => ucfirst($type),
      'source_type' => $type,
      'destination_type' => $destination_type
    );
    $arguments = array_merge_recursive($arguments, $common_node_arguments);
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'], $arguments);
  }
}

function scratchpads_migrate_term_machine_name($name){
  return 'Term' . str_replace(' ', '', ucwords($name));
}

/**
 * Mapping old node types to new entity / bundle types
 * @param string $type
 */
function scratchpads_migrate_type_mappings($type = null){
  // NB: Any node type not in this array will be created
  $mappings = array(
    'biblio' => MIGRATE_CONTENT, // migrate content only
    'blog' => MIGRATE_CONTENT, // migrate content only
    'nexus_project' => MIGRATE_NONE, // do not migrate
    'countriesmap' => MIGRATE_NONE, // do not migrate
    'forum' => MIGRATE_ALL, // migrate content only
    'glossary' => MIGRATE_NONE, // Migrate everything
    'group' => MIGRATE_NONE, // Handle groups elsewhere
    'itis_term' => MIGRATE_NONE, // do not migrate
    'image' => MIGRATE_NONE, // do not migrate
    'ispecies' => MIGRATE_NONE, // do not migrate
    'darwincorelocation' => array(
      'entity_type' => 'node',
      'bundle' => 'location'
    ),
    'simplenews' => MIGRATE_NONE, // do not migrate
    'nexus_controlled_state' => MIGRATE_NONE, // do not migrate
    'nexus_free_state' => MIGRATE_NONE, // do not migrate
    'nexus_note' => MIGRATE_NONE, // do not migrate
    'page' => MIGRATE_ALL, // migrate using the same entity & bundle type
    'tree' => MIGRATE_CONTENT, // migrate using the same entity / bundle
    'poll' => MIGRATE_NONE, // migrate using the same entity & bundle type
    'publication' => MIGRATE_NONE,
    'publication_image_caption' => MIGRATE_NONE,
    'publication_section' => MIGRATE_NONE,
    'publication_taxon_description' => MIGRATE_NONE,
    'publication_taxon_section' => MIGRATE_NONE,
    'profile' => array(
      'entity_type' => 'user',
      'bundle' => 'user',
      'fields' => array( // If fields have been renamed, map them here
        'field_title' => 'field_user_title',
        'field_givennames' => 'field_user_given_names',
        'field_familyname' => 'field_user_family_name',
        'field_institution' => 'field_user_institution',
        'field_taxonomicinterest' => 'field_user_taxonomic_interest'
      )
    ),
    'darwincore' => array(
      'entity_type' => 'node',
      'bundle' => 'specimen_observation'
    ),
    'story' => MIGRATE_NONE, // Not in use
    'spm' => MIGRATE_ALL, // migrate using the same entity & bundle type
    'webform' => MIGRATE_NONE // TODO - Webforms!!!
  );
  if($type){
    if(isset($mappings[$type])){
      return $mappings[$type];
    }else{
      return false;
    }
    return $mappings[$type];
  }else{
    return $mappings;
  }
}

function scratchpads_migrate_form_alter(&$form, &$form_state, $form_id){
  //	dd($form_id);
}


