<?php
/**
 * Add the database connection.
 * 
 * We're not adding the additional connection into the settings.php file as that
 * file is managed by Aegir.  Instead, every new site that is going to become
 * an "old" site will have an additional settings file in its files folder.
 * Simply including that file will add the additional database connection.  The
 * file should look like:
//----------
<?php
Database::addConnectionInfo('scratchpad_1', 'default', array(
  'database' => 'scratchpad_1_database',
  'username' => 'scratchpad_1_user',
  'password' => 'scratchpad_1_database_password',
  'host' => 'localhost',
  'port' => '',
  'driver' => 'mysql',
  'prefix' => ''
));
//----------
 */
require_once (drupal_realpath('public://scratchpad_1_database.php'));

/**
 * Implements hook_flush_caches().
 */
function scratchpads_migrate_flush_caches(){
  scratchpads_migrate_register_migrations();
}

/**
 * Implements hook_migrate_api().
 */
function scratchpads_migrate_migrate_api(){
  return array(
    'api' => 2
  );
}

/**
 * Register all of the migrations for this module.
 */
function scratchpads_migrate_register_migrations(){
  // The database connection to the Scratchpad 1 site.
  $common_arguments = array(
    'source_connection' => 'scratchpad_1',
    'source_version' => 6
  );
  // The description and the migration machine name are also required arguments,
  // which will be unique for each migration you register.
  $arguments = $common_arguments + array(
    'description' => t('Migration of users from Drupal 6'),
    'machine_name' => 'User'
  );
  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalUser6Migration', $arguments['machine_name'], $arguments);
}