<?php

/**
 * Implementation of hook_menu().
 */
function gm3_region_menu(){
  return array(
    'gm3_region/callback/%/%' => array(
      'title' => 'GM3 Region callback',
      'page callback' => 'gm3_region_get_points',
      'page arguments' => array(
        2,
        3
      ),
      'file' => 'gm3_region.callback.inc',
      'access arguments' => array(
        'access content'
      ),
      'type' => MENU_CALLBACK
    )
  );
}

/**
 * Implementation of hook_library().
 * 
 * FIXME - Select countries.  Click on a region could bring up an option to 
 * select the subregions (TDWG 4).
 */
function gm3_region_library(){
  // Whether or not to use the minified versions of the code.
  $min = variable_get('gm3_use_minified', false) ? '.min' : '';
  return array(
    // Enable the clicking of countries.
    'region' => array(
      'title' => t('Google Maps Javascript API V3: Region selection'),
      'website' => 'http://code.google.com/apis/maps/',
      'version' => '3',
      'js' => array(
        array(
          'data' => drupal_get_path('module', 'gm3_region') . "/js/gm3_region$min.js"
        ),
        array(
          'data' => array(
            'gm3_region' => array(
              'callback' => url('gm3_region/callback')
            )
          ),
          'type' => 'setting'
        )
      ),
      'dependencies' => array(
        array(
          'gm3',
          'gm3'
        ),
        array(
          'gm3',
          'gm3.polygon'
        )
      )
    )
  );
}

/**
 * Implementation of hook_theme().
 */
function gm3_region_theme(){
  return array(
    'gm3_region_region_button' => array(
      'variables' => array(
        'id' => 'gm3-map'
      ),
      'file' => 'gm3_region.theme.inc'
    )
  );
}

/**
 * Implementation of hook_gm3_settings_alter().
 */
function gm3_region_gm3_map_alter(&$map){
  if(isset($map['libraries'])){
    foreach($map['libraries'] as $id => $library){
      $library_name = $library;
      if(is_array($library)){
        $library_name = $id;
      }
      switch($library_name){
        case 'region':
          $map['tools'][] = theme('gm3_region_region_button', array(
            'id' => $map['id']
          ));
          break;
        default:
          break;
      }
    }
  }
}