FROM mysql:5.7

RUN yum install -y gettext && yum clean all

RUN chown root:65534 /docker-entrypoint-initdb.d && \
    chmod 2775 /docker-entrypoint-initdb.d

COPY files/master.cnf /etc/mysql/conf.d/master.cnf

COPY files/templates/init-master.sql /tmp/init-master.sql

COPY files/entrypoint-master.sh /entrypoint-master.sh
RUN chmod +x /entrypoint-master.sh

ENTRYPOINT ["/entrypoint-master.sh"]
CMD ["mysqld"]
